Unstructured-IO/docs

api-reference/api-services/aws.mdx
api-reference/api-services/azure.mdx
open-source/best-practices/overview.mdx
open-source/ingest/overview.mdx
platform/jobs-scheduling.mdx
platform/platform-destination-connectors/azure-cognitive-search.mdx
platform/platform-destination-connectors/chroma.mdx
platform/platform-destination-connectors/databricks.mdx
platform/platform-destination-connectors/elasticsearch.mdx
platform/platform-destination-connectors/google-cloud-storage.mdx
platform/platform-destination-connectors/mongodb.mdx
platform/platform-destination-connectors/opensearch.mdx
platform/platform-destination-connectors/overview.mdx
platform/platform-destination-connectors/pinecone.mdx
platform/platform-destination-connectors/postgresql.mdx
platform/platform-destination-connectors/s3.mdx
platform/platform-destination-connectors/weaviate.mdx
platform/platform-source-connectors/azure-blob-storage.mdx
platform/platform-source-connectors/elasticsearch.mdx
platform/platform-source-connectors/google-cloud.mdx
platform/platform-source-connectors/google-drive.mdx
platform/platform-source-connectors/onedrive-cloud-storage.mdx
platform/platform-source-connectors/opensearch.mdx
platform/platform-source-connectors/overview.mdx
platform/platform-source-connectors/s3.mdx
platform/platform-source-connectors/salesforce.mdx
platform/platform-source-connectors/sftp-storage.mdx
platform/platform-source-connectors/sharepoint.mdx
platform/workflows-automation.mdx

The path to images that renders in local preview doesn't seem to render for the deployed docs. 
Updated the paths to images. This should hopefully fix it.

Images chore: path fix

---

open-source/installation/docker-installation.mdx
open-source/installation/full-installation.mdx
open-source/installation/overview.mdx
open-source/introduction/overview.mdx
open-source/introduction/quick-start.mdx

This PR: 
* Improves the overview page of for the Open Source library
* Fixes some formatting issues
* Improves suboptimal wording on the "installation overview" page

Misc improvements to the docs

---

script.js

The PR adds the script tag to enable kapa.ai widget.

Script for kapa.ai

---

script.js

Updated script to enable kapa.ai

Script for kapa.ai update

---

open-source/core-functionality/cleaning.mdx
open-source/core-functionality/extracting.mdx
open-source/core-functionality/partitioning.mdx
open-source/core-functionality/staging.mdx
openapi.json

Some GH links were pointing to a specific commit, now they point to main to stay up to date.

Chore: fixed GH links to point to main

---

mint.json
platform/jobs-scheduling.mdx
platform/workflows-automation.mdx

Updated Nav for platform to be closer to API for consistency

Refactored new platform section nav to be closer to api nav

---

.speakeasy/workflow.yaml

Added through `speakeasy configure sources`.

fix: Update workflow.yaml to support Mintlify

---

snippets/concepts/glossary.mdx

Two broken links on glossary page fixed

Fixed broken links on glossary

---

open-source/core-functionality/embedding.mdx

Adding VertexAIEmbeddingEncoder description

Adding VoyageAI EmbeddingEncoder description to embedding.mdx

---

faq/faq.mdx
open-source/core-functionality/staging.mdx
open-source/introduction/overview.mdx
open-source/introduction/quick-start.mdx
platform/overview.mdx
platform/saas-platform-guide.mdx

The PR fixes all of the broken links in the docs. 
This can be checked by running `mintlify broken-links` in the terminal

Fixed all remaining broken links

---

snippets/concepts/glossary.mdx

Milvus support is planned for Q3, and the mention got into the docs by mistake. Removed.

Removed Milvus as it's not supported yet

---

api-reference/api-services/saas-api-development-guide.mdx
api-reference/api-services/sdk.mdx
faq/faq.mdx
welcome.mdx

**DO NOT MERGE UNTIL API LAUNCH**
This PR includes updates to the Getting Started docs for the new API (linked from the dashboard).

Updates to SaaS API Getting started page

---

api-reference/api-services/saas-api-development-guide.mdx

Rephrased mentions of the API URL to avoid confusion.

minor updates re api url

---

examplecode/notebooks.mdx

Swapping out demo notebook with the structure for API v2

Update notebooks.mdx with Serverless API doc

---

api-reference/api-services/azure.mdx

Minor updates for grammar, UI casing, consistency, `curl` command formatting, and the like: https://unstructured-53-docs-3-azure.mintlify.app/api-reference/api-services/azure
Testing: I ran through all of these steps in an Azure account to make sure they were currently accurate.

Minor updates to Unstructured API on Azure deployment

---

api-reference/api-services/aws.mdx

Minor updates for grammar, UI casing, consistency, curl command formatting, and the like: https://unstructured-53-docs-4-aws.mintlify.app/api-reference/api-services/aws
Testing: I ran through all of these steps in an AWS account to make sure they were currently accurate.

Minor updates to Unstructured API on AWS deployment

---

api-reference/api-services/free-api.mdx
api-reference/api-services/saas-api-development-guide.mdx
open-source/introduction/overview.mdx
snippets/general-shared-text/telemetry.mdx

See https://github.com/Unstructured-IO/docs/issues/45.

How to turn off telemetry

---

open-source/core-functionality/chunking.mdx

See https://github.com/Unstructured-IO/docs/issues/53. Created a code example based on my conversation with @scanny.

orig_elements deserialization examples

---

open-source/introduction/overview.mdx
welcome.mdx

Several customers are asking for a more complete list than what we currently present in somewhat small-ish font in the current sidebar note. Here's my attempt at this: https://unstructured-53-open-source-diffs.mintlify.app/open-source/introduction/overview#limits

Enumerate open-source library limits

---

api-reference/api-services/accessing-unstructured-api.mdx
api-reference/api-services/aws.mdx
api-reference/api-services/azure.mdx
api-reference/api-services/free-api.mdx
api-reference/api-services/partition-via-api.mdx
api-reference/api-services/post-requests.mdx
api-reference/api-services/saas-api-development-guide.mdx
api-reference/api-services/sdk.mdx
open-source/introduction/quick-start.mdx
snippets/general-shared-text/multi-file-api-use-connectors.mdx
snippets/general-shared-text/multi-file-oss-use-connectors.mdx
snippets/general-shared-text/multi-file-partition-via-api.mdx
snippets/general-shared-text/post-api-single-file.mdx

Processing multiple files at a time requires different coding approaches over their single-file counterparts. This PR seeks to guide users through the right approach depending on their needs.

Multi-file processing: code approaches

---

examplecode/notebooks.mdx

Updated the list of notebooks, removed numbered icons

---

api-reference/api-services/free-api.mdx
api-reference/api-services/overview.mdx
api-reference/api-services/saas-api-development-guide.mdx
api-reference/api-services/sdk.mdx
snippets/general-shared-text/api-key-differences.mdx
snippets/general-shared-text/free-api-key-no-serverless-access.mdx
snippets/general-shared-text/serverless-api-key-no-free-access.mdx
welcome.mdx

Added more visual Mintlify features, guided cross-links, and clarifications to the getting started pages and quickstarts.
Some of this is to make the pages more visually appealing and navigable, some of this is in response to some related support and feedback reqeusts. 
See:
- Docs home page: https://unstructured-53-api-key-differences-2024-07-18.mintlify.app/welcome
- API home page: https://unstructured-53-api-key-differences-2024-07-18.mintlify.app/api-reference/api-services/overview
- Serverless API home page: https://unstructured-53-api-key-differences-2024-07-18.mintlify.app/api-reference/api-services/saas-api-development-guide
- Free API home page: https://unstructured-53-api-key-differences-2024-07-18.mintlify.app/api-reference/api-services/free-api

More getting started improvements

---

api-reference/how-to/change-chunking-strategy.mdx
api-reference/how-to/change-element-coordinate-system.mdx
api-reference/how-to/change-partitioning-strategy.mdx
api-reference/how-to/extract-image-block-types.mdx
api-reference/how-to/output-bounding-box-coordinates.mdx
api-reference/how-to/output-unique-element-ids.mdx
api-reference/how-to/parse-simple-pdf-html.mdx
api-reference/how-to/powerpoint.mdx
api-reference/how-to/set-document-language-ocr.mdx
api-reference/how-to/use-langchain-llama-3.mdx
api-reference/how-to/use-langchain-ollama.mdx
mint.json

See the "How To" list on the Table of Contents on the sidebar (you might need to scroll down on that page to see it): https://unstructured-53-how-to-2024-07-19.mintlify.app/api-reference/api-services/overview
Feel free to suggest more! 😄

Stub in more how-to TOC refs

---

mint.json
open-source/how-to/set-ocr-agent.mdx
snippets/how-to-oss/set_ocr_agent.py.mdx

First "how-to" doc for OSS! 😄 Addresses https://github.com/Unstructured-IO/docs/issues/54. Applies to OSS only. See: https://unstructured-53-set-ocr-agent-oss-2024-07-23.mintlify.app/open-source/how-to/set-ocr-agent

How to set the OCR agent to use

---

snippets/ingest-configuration-shared/chunking-configuration.mdx
snippets/ingest-configuration-shared/embedding-configuration.mdx
snippets/ingest-configuration-shared/fsspec-configuration.mdx
snippets/ingest-configuration-shared/partition-configuration.mdx
snippets/ingest-configuration-shared/permissions-configuration.mdx
snippets/ingest-configuration-shared/processor-configuration.mdx
snippets/ingest-configuration-shared/read-configuration.mdx
snippets/ingest-configuration-shared/retry-strategy-configuration.mdx

Will need help filling in all of the blank ones! 
See:
- Processor Configuration: https://unstructured-53-update-ingest-params-2024-07-24.mintlify.app/api-reference/ingest/ingest-configuration/processor-configuration
- Read Configuration: https://unstructured-53-update-ingest-params-2024-07-24.mintlify.app/api-reference/ingest/ingest-configuration/read-configuration
- Partition Configuration: https://unstructured-53-update-ingest-params-2024-07-24.mintlify.app/api-reference/ingest/ingest-configuration/partition-configuration
- Permissions Configuration: https://unstructured-53-update-ingest-params-2024-07-24.mintlify.app/api-reference/ingest/ingest-configuration/permissions-configuration
- Retry Strategy Configuration: https://unstructured-53-update-ingest-params-2024-07-24.mintlify.app/ap …

Add missing ingest v1 and v2 parameters, note which are v1 and v2

---

api-reference/best-practices/speed-up-large-files-batches.mdx
mint.json

See https://unstructured-53-speed-up-large-files-batches-2024-07-24.mintlify.app/api-reference/best-practices/speed-up-large-files-batches

How to speed up large files and batches of files

---

open-source/core-functionality/partitioning.mdx

See https://github.com/Unstructured-IO/unstructured/pull/3446

update docs to include info about bcc, cc, and message id for email and msg partitioning

---

api-reference/how-to/get-elements.mdx
mint.json

This PR attempts to address a basic question coming in a lot through the AI search component in the docs. 
See https://unstructured-53-docs-47-get-elements.mintlify.app/api-reference/how-to/get-elements

API: How to access elements and metadata

---

examplecode/notebooks.mdx

The PR adds a new notebook to Example Code featuring SingleStore DB integration example: 
https://unstructured-53-singlestore-notebook.mintlify.app/examplecode/notebooks

SingleStore notebook

---

api-reference/ingest/destination-connector/sql.mdx
open-source/ingest/destination-connectors/sql.mdx
snippets/dc-shared-text/s3-cli-api.mdx
snippets/dc-shared-text/sql-cli-api.mdx
snippets/destination_connectors/sql.sh.mdx
snippets/destination_connectors/sql.v1.py.mdx
snippets/destination_connectors/sql.v2.py.mdx
snippets/general-shared-text/sql-cli-api.mdx
snippets/general-shared-text/sql-sample-index-schema.mdx
snippets/general-shared-text/sql.mdx

See: 
- API: https://unstructured-53-docs-36-sql.mintlify.app/api-reference/ingest/destination-connector/sql
- Open source: https://unstructured-53-docs-36-sql.mintlify.app/open-source/ingest/destination-connectors/sql

PostgreSQL and SQLite v2 destination connector

---

examplecode/notebooks.mdx

See the last/bottom-most tile in https://unstructured-53-huggingchat-notebook-2024-08-08.mintlify.app/examplecode/notebooks

Notebook example: Query processed PDF with HuggingChat

---

examplecode/codesamples/api/huggingchat.mdx
mint.json
snippets/examples/huggingchat.ts.mdx

See https://unstructured-53-rag-sample-js-ts-2024-08-12.mintlify.app/examplecode/codesamples/api/huggingchat

Code example: Use the JS/TS SDK to query processed PDF with HuggingChat

---

api-reference/api-services/overview.mdx
api-reference/how-to/choose-hi-res-model.mdx
api-reference/how-to/choose-partitioning-strategy.mdx
api-reference/how-to/extract-image-block-types.mdx
api-reference/how-to/text-as-html.mdx
mint.json
open-source/concepts/models.mdx
open-source/ingest/destination-connectors/overview.mdx
open-source/ingest/source-connectors/overview.mdx
open-source/introduction/overview.mdx

Covers:
- New decision-makers for how to choose a partitioning strategy and how to choose a hi-res model. 
- Benefits to using the Unstructured Serverless API over the Unstructured open-source library. (This is already in the open-source docs but not yet in the Serverless API docs.)
- Updated a how-to's title from "Extract image block types" to "Extract images and tables from documents."
- Some very minor page re-titling for consistency across the docs. 
See:
- https://unstructured-53-customer-feedback-2024-08-09.mintlify.app/api-reference/how-to/choose-partitioning-strategy
- https://unstructured-53-customer-feedback-2024-08-09.mintlify.app/api-reference/how-to/choose-hi-res-model
- https://unstructured-53-customer-feedback-2024-08-09.mintlify.app/api-reference/how-to/extract-image-block- …

Customer feedback roundup

---

snippets/ingest-configuration-shared/processor-configuration.mdx

Ingest processor config settings: max_docs, re_download, and uncompress

---

api-reference/api-services/overview.mdx
api-reference/api-services/supported-file-types.mdx
mint.json
open-source/introduction/overview.mdx
open-source/introduction/supported-file-types.mdx
snippets/general-shared-text/supported-file-types.mdx
welcome.mdx

See:
- Welcome page: https://unstructured-53-file-types-2024-08-15.mintlify.app/welcome#supported-file-types
- API: https://unstructured-53-file-types-2024-08-15.mintlify.app/api-reference/api-services/supported-file-types
- Open source: https://unstructured-53-file-types-2024-08-15.mintlify.app/open-source/introduction/supported-file-types

Supported file types

---

api-reference/how-to/embedding.mdx
mint.json

See https://unstructured-53-embedding-2024-08-19.mintlify.app/api-reference/how-to/embedding

How-to mechanics for specifying embedding models

---

api-reference/api-services/examples.mdx
api-reference/how-to/choose-partitioning-strategy.mdx

See https://unstructured-53-use-ingest-more-notes-2024-08-21.mintlify.app/api-reference/api-services/examples#ingest-python

Add Ingest examples to API examples page

---

api-reference/ingest/overview.mdx

See https://unstructured-53-pipeline-flow-2024-08-22.mintlify.app/api-reference/ingest/overview#ingest-flow

Ingest pipeline flow diagram and explanation

---

examplecode/codesamples/api/huggingchat.mdx
snippets/examples/huggingchat.py.mdx
snippets/examples/huggingchat.ts.mdx

See https://unstructured-53-huggingchat-ingest-2024-08-23.mintlify.app/examplecode/codesamples/api/huggingchat

HuggingChat example: added Ingest Python library example

---

platform/overview.mdx

See the "Enrich" step (step #5) in https://unstructured-53-ingest-pipeline-flow-summaries-2024-08-26.mintlify.app/platform/overview#how-does-it-work

Add Enrich step to Ingest pipeline flow

---

api-reference/how-to/filter-files.mdx
mint.json

See https://unstructured-53-docs-59-filter-docs.mintlify.app/api-reference/how-to/filter-files

How to process a subset of files

---

api-reference/api-services/aws.mdx
api-reference/api-services/azure.mdx
snippets/how-to-api/azure-aws.mdx

See https://unstructured-53-docs-58-azure-settings.mintlify.app/api-reference/api-services/azure

Azure Marketplace API: added load balancer and environment variable settings

---

api-reference/api-services/azure.mdx

These steps were listed incorrectly in https://github.com/Unstructured-IO/docs/pull/202. This PR is a fast follow to that one to make this correction. 
See

Azure Marketplace API: how to set environment variables in a container

---

api-reference/ingest/destination-connector/chroma.mdx
open-source/ingest/destination-connectors/chroma.mdx
snippets/dc-shared-text/chroma-cli-api.mdx
snippets/destination_connectors/chroma.sh.mdx
snippets/destination_connectors/chroma.v1.py.mdx
snippets/destination_connectors/chroma.v2.py.mdx
snippets/general-shared-text/chroma-cli-api.mdx
snippets/general-shared-text/chroma.mdx

See:
- API: https://unstructured-53-docs-36-chroma.mintlify.app/api-reference/ingest/destination-connector/chroma
- Open source: https://unstructured-53-docs-36-chroma.mintlify.app/open-source/ingest/destination-connectors/chroma

Chroma v2 destination connector

---

api-reference/api-services/examples.mdx
api-reference/api-services/saas-api-development-guide.mdx
api-reference/how-to/choose-hi-res-model.mdx
api-reference/how-to/choose-partitioning-strategy.mdx
api-reference/how-to/embedding.mdx
api-reference/ingest/destination-connector/pinecone.mdx
api-reference/ingest/source-connectors/s3.mdx
open-source/ingest/destination-connectors/pinecone.mdx
open-source/ingest/source-connectors/s3.mdx
platform/overview.mdx
welcome.mdx

See: 
- Welcome page, first video from top of this page: https://unstructured-53-video-links-2024-09-05.mintlify.app/welcome
- How to change the partitioning strategy for a PDF: https://unstructured-53-video-links-2024-09-05.mintlify.app/api-reference/api-services/examples
- How to specify a Hi-Res model: 
- https://unstructured-53-video-links-2024-09-05.mintlify.app/api-reference/how-to/choose-hi-res-model
- https://unstructured-53-video-links-2024-09-05.mintlify.app/api-reference/how-to/choose-partitioning-strategy
- How to generate embeddings: https://unstructured-53-video-links-2024-09-05.mintlify.app/api-reference/how-to/embedding
- How to set up Pinecone as a destination: 
- https://unstructured-53-video-links-2024-09-05.mintlify.app/api-reference/ingest/destination-connector/pinecon …

Embedding more video how-to's

---

platform/jobs-scheduling.mdx
platform/workflows-automation.mdx

- **Show Ad Hoc Jobs** toggle has been removed from **Jobs** page. 
- Workflow statuses have been removed from **Workflows** page.
- Job status labels have changed in **Jobs** page.
- Some **Job Details** labels have changed.

Platform UI: minor updates

---

snippets/general-shared-text/azure.mdx

See:
- Platform: https://unstructured-53-docs-61-azure-blob-storage.mintlify.app/platform/platform-source-connectors/azure-blob-storage
- API: https://unstructured-53-docs-61-azure-blob-storage.mintlify.app/api-reference/ingest/source-connectors/azure
- Open source: https://unstructured-53-docs-61-azure-blob-storage.mintlify.app/open-source/ingest/source-connectors/azure

Azure source connector: embedded videos for how to set up Azure storage

---

api-reference/how-to/embedding.mdx

See Bedrock-related content in https://unstructured-53-bedrock-2024-09-10.mintlify.app/api-reference/how-to/embedding#generate-embeddings

Bedrock embeddings: where to find and how to specify models

---

api-reference/how-to/embedding.mdx
api-reference/ingest/ingest-dependencies.mdx
snippets/ingest-configuration-shared/embedding-configuration.mdx

Mixedbread: adding embedding details

---

mint.json
platform/chunking.mdx

We have this in the API and open-source library sections, but it has lots of API- and code-focused content. This PR attempts to present this content from a Platform-centric perspective.
See https://unstructured-53-docs-65-chunking.mintlify.app/platform/chunking

Platform docs: chunking concepts from a Platform perspective

---

snippets/general-shared-text/onedrive.mdx

Same video links across all of these pages. See:
- Platform:
- API:
- Open source:

OneDrive source connector: how-to video links

---

examplecode/notebooks.mdx

This way it should automatically open in Colab

Better singlestoreDB notebook link

---

openapi.json

Copy over the latest API spec from https://api.unstructured.io/general/openapi.json, for use in our API playground.

chore: update openapi.json

---

api-reference/ingest/destination-connector/s3.mdx
api-reference/ingest/source-connectors/s3.mdx
open-source/ingest/destination-connectors/s3.mdx
open-source/ingest/source-connectors/s3.mdx
platform/destinations/s3.mdx
platform/sources/s3.mdx
snippets/general-shared-text/s3-bucket-policy.mdx
snippets/general-shared-text/s3.mdx

See the staged builds (video and policy how-to's are the same across all of these pages):
- Platform:
- Source: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/platform/sources/s3
- Destination: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/platform/destinations/s3
- API:
- Source: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/api-reference/ingest/source-connectors/s3
- Destination: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/api-reference/ingest/destination-connector/s3
- Open source:
- Source: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/open-source/ingest/source-connectors/s3
- Destination: https://unstructured-53-platform-s3-2024-09-25.mintlify.app/open-source/ingest/destination-connectors/s3

S3 connectors: bucket setup how-to video, copyable access policy

---

mint.json
platform/connectors.mdx
platform/destinations/overview.mdx
platform/overview.mdx
platform/partitioning.mdx
platform/sources/overview.mdx
platform/workflows.mdx
snippets/quickstarts/platform.mdx

Hide all Platform connectors except Azure and S3 for sources and Azure Cognitive Search, Pinecone, and S3 for destinations. Also update latest Basic and Advanced default workflow settings. 
Of particular interest here: 
- Supported connectors: https://unstructured-53-platform-align-2024-09-25.mintlify.app/platform/connectors
- Quickstart: https://unstructured-53-platform-align-2024-09-25.mintlify.app/platform/quickstart
- Sources: https://unstructured-53-platform-align-2024-09-25.mintlify.app/platform/sources/overview
- Destinations: https://unstructured-53-platform-align-2024-09-25.mintlify.app/platform/destinations/overview
- Create a workflow, plus Basic and Advanced default workflow settings: https://unstructured-53-platform-align-2024-09-25.mintlify.app/platform/workflows

Platform UI: latest list of available connectors, workflow settings

---

platform/destinations/pinecone.mdx
snippets/general-shared-text/azure-cognitive-search.mdx
snippets/general-shared-text/azure.mdx

Previews:
- Pinecone (shows use of Platform, so only embed-linked from Platform doc):
- Platform: https://unstructured-53-embed-videos-2024-09-26.mintlify.app/platform/destinations/pinecone
- Azure Cognitive Search:
- Platform: https://unstructured-53-embed-videos-2024-09-26.mintlify.app/platform/destinations/azure-cognitive-search
- API: https://unstructured-53-embed-videos-2024-09-26.mintlify.app/api-reference/ingest/destination-connector/azure-cognitive-search
- Open source: https://unstructured-53-embed-videos-2024-09-26.mintlify.app/open-source/ingest/destination-connectors/azure-cognitive-search
- Azure Storage:
- Platform: https://unstructured-53-embed-videos-2024-09-26.mintlify.app/platform/sources/azure-blob-storage
- API:
- Source: …

More embed-linked videos to connectors for Pinecone, Azure Cognitive Search, and Azure Storage

---

snippets/general-shared-text/s3.mdx

Had to reshoot and re-upload video, which resulted in a new/replacement URL.

S3 connector: fix video embed link

---

api-reference/api-services/overview.mdx
open-source/introduction/overview.mdx
platform/overview.mdx

Support for SOC2 Type 1, SOC2 Type 2, and HIPAA compliance

---

open-source/core-functionality/partitioning.mdx

See https://github.com/Unstructured-IO/unstructured/issues/3671

Open source: remove attachment_partitioner from partition_msg and partition_email

---

api-reference/how-to/transform-schemas.mdx
mint.json

See https://unstructured-53-json-schema-transforms.mintlify.app/api-reference/how-to/transform-schemas

How to transform Unstructured JSON to a custom JSON schema

---

snippets/general-shared-text/milvus.mdx

See:
* https://unstructured-53-milvus-video-2024-10-07.mintlify.app/api-reference/ingest/destination-connector/milvus
* https://unstructured-53-milvus-video-2024-10-07.mintlify.app/open-source/ingest/destination-connectors/milvus

Embed-link Milvus setup how-to video on Milvus connector pages

---

snippets/general-shared-text/databricks-volumes.mdx

See:
- https://unstructured-53-databricks-volumes-video-2024-10-09.mintlify.app/api-reference/ingest/destination-connector/databricks-volumes
- https://unstructured-53-databricks-volumes-video-2024-10-09.mintlify.app/open-source/ingest/destination-connectors/databricks-volumes

Add embed-linked video for Databricks Volumes setup

---

api-reference/api-services/aws.mdx

AWS Marketplace offering: how to manage related costs

---

api-reference/ingest/source-connectors/mongodb.mdx
open-source/ingest/source-connectors/mongodb.mdx
snippets/source_connectors/mongodb.v2.py.mdx

See:
- https://unstructured-53-api-mongodb-destination-2024-10-18.mintlify.app/api-reference/ingest/source-connectors/mongodb
- https://unstructured-53-api-mongodb-destination-2024-10-18.mintlify.app/open-source/ingest/source-connectors/mongodb

MongoDB v2 source connector

---

mint.json
platform/connectors.mdx
platform/destinations/astradb.mdx
platform/overview.mdx
snippets/general-shared-text/astradb-platform.mdx

See https://unstructured-53-astradb-destination-platform-2024-10-21.mintlify.app/platform/destinations/astradb

Astra DB destination connector for Platform

---

mint.json
platform/connectors.mdx
platform/sources/overview.mdx

See https://unstructured-53-sharepoint-source-platform-2024-10-21.mintlify.app/platform/sources/sharepoint

SharePoint source connector for Platform

---

api-reference/ingest/destination-connector/snowflake.mdx
api-reference/ingest/ingest-dependencies.mdx
api-reference/ingest/source-connectors/snowflake.mdx
mint.json
open-source/ingest/destination-connectors/snowflake.mdx
open-source/ingest/source-connectors/snowflake.mdx
snippets/dc-shared-text/snowflake-cli-api.mdx
snippets/destination_connectors/snowflake.sh.mdx
snippets/destination_connectors/snowflake.v2.py.mdx
snippets/general-shared-text/snowflake-cli-api.mdx
snippets/general-shared-text/snowflake.mdx
snippets/sc-shared-text/snowflake-cli-api.mdx
snippets/source_connectors/snowflake.sh.mdx
snippets/source_connectors/snowflake.v2.py.mdx

See:
- https://unstructured-53-snowflake-connectors-2024-10-24.mintlify.app/api-reference/ingest/source-connectors/snowflake
- https://unstructured-53-snowflake-connectors-2024-10-24.mintlify.app/api-reference/ingest/destination-connector/snowflake
- https://unstructured-53-snowflake-connectors-2024-10-24.mintlify.app/open-source/ingest/source-connectors/snowflake
- https://unstructured-53-snowflake-connectors-2024-10-24.mintlify.app/open-source/ingest/destination-connectors/snowflake

Snowflake v2 API source and destination connectors

---

mint.json

Google Measurement ID provided by AK.

Enable Google Analytics 4

---

platform/embedding.mdx
platform/workflows.mdx
snippets/ingest-configuration-shared/embedding-configuration.mdx

See:
- https://unstructured-53-embedding-dimensions-2024-10-28.mintlify.app/platform/workflows#build-it-with-me-custom (see Step 16)
- https://unstructured-53-embedding-dimensions-2024-10-28.mintlify.app/platform/workflows#custom-workflow-node-types (expand "Embedder node" section)
- https://unstructured-53-embedding-dimensions-2024-10-28.mintlify.app/platform/embedding (scroll to bottom/end of page)
- https://unstructured-53-embedding-dimensions-2024-10-28.mintlify.app/api-reference/ingest/ingest-configuration/embedding-configuration (scroll to bottom/end of page)

Added embedding dimensions by model

---

platform/workflows.mdx
snippets/quickstarts/platform.mdx

Phrasing approved by Sudarshan.
See:
- https://unstructured-53-reprocess-all-2024-10-30.mintlify.app/platform/quickstart (Step 9)
- https://unstructured-53-reprocess-all-2024-10-30.mintlify.app/platform/workflows#build-it-with-me-custom (Step 17)
- https://unstructured-53-reprocess-all-2024-10-30.mintlify.app/platform/workflows#build-it-myself (Step 7)

Platform: "Reprocess all" check box applies only to S3 and Azure source connectors

---

snippets/general-shared-text/sharepoint.mdx

See (same target content in all pages):
- https://unstructured-53-sharepoint-policy-2024-11-04.mintlify.app/platform/sources/sharepoint
- https://unstructured-53-sharepoint-policy-2024-11-04.mintlify.app/api-reference/ingest/source-connectors/sharepoint
- https://unstructured-53-sharepoint-policy-2024-11-04.mintlify.app/open-source/ingest/source-connectors/sharepoint

SharePoint connectors: add app permission request XML examples, use correct conventions for required/optional

---

snippets/general-shared-text/gcs.mdx

See (same video for all of these pages):
-

Google Cloud Storage connector docs: video how-to embed link

---

mint.json
platform/connectors.mdx
platform/destinations/overview.mdx
snippets/general-shared-text/weaviate-platform.mdx
snippets/general-shared-text/weaviate.mdx

See:
- https://unstructured-53-weaviate-platform-dest-conn-2024-11-13.mintlify.app/platform/destinations/weaviate
- https://unstructured-53-weaviate-platform-dest-conn-2024-11-13.mintlify.app/api-reference/ingest/destination-connector/weaviate
- https://unstructured-53-weaviate-platform-dest-conn-2024-11-13.mintlify.app/open-source/ingest/destination-connectors/weaviate

Platform: Weaviate destination connector

---

mint.json
platform/connectors.mdx
platform/destinations/couchbase.mdx
platform/destinations/overview.mdx
snippets/general-shared-text/couchbase-platform.mdx
snippets/general-shared-text/couchbase.mdx

See: 
- https://unstructured-53-couchbase-platform-conn-2024-11-14.mintlify.app/platform/destinations/couchbase
- https://unstructured-53-couchbase-platform-conn-2024-11-14.mintlify.app/api-reference/ingest/destination-connector/couchbase
- https://unstructured-53-couchbase-platform-conn-2024-11-14.mintlify.app/open-source/ingest/destination-connectors/couchbase

Platform: Couchbase destination connector

---

snippets/general-shared-text/confluence.mdx

See:
- https://unstructured-53-confluence-video-2024-11-20.mintlify.app/api-reference/ingest/source-connectors/confluence
- https://unstructured-53-confluence-video-2024-11-20.mintlify.app/open-source/ingest/source-connectors/confluence

Add Confluence video how-to embed link

---

mint.json
platform/connectors.mdx
platform/sources/confluence.mdx
platform/sources/overview.mdx
snippets/general-shared-text/confluence-platform.mdx

See https://unstructured-53-confluence-platform-source-2024-11-19.mintlify.app/platform/sources/confluence

Platform: Confluence source connector

---

mint.json
platform/connectors.mdx
platform/sources/outlook.mdx
platform/sources/overview.mdx
snippets/general-shared-text/outlook-platform.mdx
snippets/general-shared-text/outlook.mdx

See https://unstructured-53-outlook-platform-source-2024-11-20.mintlify.app/platform/sources/outlook

Platform: Outlook source connector

---

platform/supported-file-types.mdx
snippets/general-shared-text/supported-file-types-platform.mdx

Waiting for guidance from @cmscmadd 
See https://unstructured-53-platform-more-file-types.mintlify.app/platform/supported-file-types

[Hold] Platform: Supported file types

---

mint.json

Discussed design with Nina via Slack.

Add llms.txt and variants to sidebar navigation

---

snippets/general-shared-text/weaviate.mdx

The old video shows how to create a collection in Weaviate that might produce unexpected results in some cases with Unstructured.
See for example https://unstructured-53-weaviate-video-2024-12-11.mintlify.app/platform/destinations/weaviate

Weaviate connector: swap how-to video embed links

---

snippets/general-shared-text/postgresql.mdx

See for example https://unstructured-53-azure-postgresql-video-2025-01-06.mintlify.app/platform/destinations/postgresql (2nd and 3rd of the three videos on this page)

PostgreSQL connectors: videos for how to set up Azure Database for PostgreSQL and how to use the psql utility

---

platform/workflows.mdx
snippets/quickstarts/platform.mdx

See the "Files changed" tab for "before" and "after" phrasing. (The "before" and "after" phrasing changes are identical in all of the instances.)

Reprocess All Files check box: Updated description of checked/unchecked behaviors

---

snippets/general-shared-text/milvus-platform.mdx

See the bottom/end of https://unstructured-53-milvus-vendors-platform-2025-01-06.mintlify.app/platform/destinations/milvus

Milvus destination connector: Platform UI updates for different vendor types

---

examplecode/notebooks.mdx

The PR adds a new notebook to the Example Code page, and missing tags

Agentic RAG notebook + missing tags

---

platform/summarizing.mdx
platform/workflows.mdx

See:
- https://unstructured-53-openai-table-summarizer-2024-01-14.mintlify.app/platform/workflows#build-it-with-me-custom -> Step 11
- https://unstructured-53-openai-table-summarizer-2024-01-14.mintlify.app/platform/workflows#enrichment-node
- https://unstructured-53-openai-table-summarizer-2024-01-14.mintlify.app/platform/summarizing -> bottom of page

Platform: Add support for OpenAI GPT-4o table to HTML enrichments

---

snippets/general-shared-text/kafka.mdx
snippets/general-shared-text/neo4j.mdx

See for example:
- https://unstructured-53-docs-133-134-neo4j-kafka-videos.mintlify.app/api-reference/ingest/destination-connector/kafka
- https://unstructured-53-docs-133-134-neo4j-kafka-videos.mintlify.app/api-reference/ingest/destination-connector/neo4j

How-to video embed links for Kafka and Neo4j connectors

---

snippets/general-shared-text/google-drive.mdx

See for example https://unstructured-53-google-drive-connector-enable-api-2025-01-16.mintlify.app/platform/sources/google-drive

Google Drive source connector: even more setup details, based on customer feedback

---

platform/api/overview.mdx

See https://unstructured-53-platform-api-video-2025-01-16.mintlify.app/platform/api/overview

Platform API: how-to video embed liink

---

snippets/general-shared-text/dropbox.mdx

See for example https://unstructured-53-dropbox-video-2025-01-23.mintlify.app/platform/sources/dropbox

Dropbox connectors: add embed link to replacement how-to video

---

platform/embedding.mdx
platform/workflows.mdx

These were originally displayed in the UI but were removed later.

Platform: Together AI - remove Sentence-BERT and BERT models

---

snippets/destination_connectors/snowflake.sh.mdx
snippets/destination_connectors/snowflake.v2.py.mdx
snippets/general-shared-text/snowflake-cli-api.mdx
snippets/general-shared-text/snowflake.mdx
snippets/source_connectors/snowflake.sh.mdx
snippets/source_connectors/snowflake.v2.py.mdx

See: 
- https://unstructured-53-docs-144-snowflake.mintlify.app/api-reference/ingest/source-connectors/snowflake
- https://unstructured-53-docs-144-snowflake.mintlify.app/api-reference/ingest/destination-connector/snowflake
- https://unstructured-53-docs-144-snowflake.mintlify.app/open-source/ingest/source-connectors/snowflake
- https://unstructured-53-docs-144-snowflake.mintlify.app/open-source/ingest/destination-connectors/snowflake

Ingest v2: Snowflake connectors - add example SQL statements and more how-to instructions, and expand details for role and unique record ID

---

platform/workflows.mdx
snippets/quickstarts/platform.mdx

Confirmed with PM that this has now been removed for all users.
Content removed from https://unstructured-53-docs-145-platform-custom.mintlify.app/platform/workflows

[Hold] Platform: Remove Custom option from 'build it with me' workflow type selector

---

snippets/general-shared-text/onedrive.mdx

While troubleshooting with a customer, we determined that the OneDrive and SharePoint license requirements are a bit more strict than what we originally tested with.
See for example https://unstructured-53-onedrive-licensing-2025-01-31.mintlify.app/platform/sources/onedrive -> first three bullet points in the requirements list

OneDrive connectors: more detailed OneDrive and SharePoint license requirements

---

mint.json

See https://unstructured-53-trust-center-2025-01-31.mintlify.app/welcome -> left-hand TOC navigation - "Trust Portal" icon for treatment

Add Trust Portal link to quicklinks list in the TOC

---

rb2b.js

Integrate RB2B script. Requested by Orlando.

RB2B script

---

snippets/general-shared-text/onedrive.mdx

Rather than re-re-shoot the monolithic OneDrive how-to video for some requested changes, I'm breaking this up into smaller videos for easier maintenance in the future if needed.
See for example https://unstructured-53-onedrive-videos-2025-02-05.mintlify.app/platform/sources/onedrive

OneDrive connectors: new how-to video embed links

---

snippets/general-shared-text/snowflake.mdx

See for example https://unstructured-53-docs-157-snowflake-videos.mintlify.app/api-reference/ingest/destination-connector/snowflake

Snowflake connectors: how-to video embed links

---

snippets/general-shared-text/redis.mdx

See http://unstructured-53-docs-161-redis-video.mintlify.app/api-reference/ingest/destination-connector/redis

Redis destination connector: add setup how-to video embed link

---

platform/api/workflows.mdx

See https://unstructured-53-docs-195-platform-rest-api-custom-workflows.mintlify.app/platform/api/workflows

Platform REST API: Add custom workflow node types

---

platform/embedding.mdx
platform/workflows.mdx

This is now available to all Platform users.
See:
- https://unstructured-53-docs-196-voyageai-embed.mintlify.app/platform/embedding
- https://unstructured-53-docs-196-voyageai-embed.mintlify.app/platform/workflows#embedder-node

Platform: Add Voyage AI embedding provider and models

---

mint.json
platform-api/api/sources/box.mdx
platform-api/api/sources/overview.mdx
platform/connectors.mdx
platform/sources/box.mdx
platform/sources/overview.mdx
snippets/general-shared-text/box-api-placeholders.mdx
snippets/general-shared-text/box-cli-api.mdx
snippets/general-shared-text/box-platform.mdx
snippets/general-shared-text/box.mdx
snippets/source_connectors/box_rest_change.mdx
snippets/source_connectors/box_rest_create.mdx
snippets/source_connectors/box_sdk.mdx

See:
- https://unstructured-53-box-platform-2025-02-27.mintlify.app/platform/sources/box
- https://unstructured-53-box-platform-2025-02-27.mintlify.app/platform-api/api/sources/box

Platform: Box source connector

---

open-source/introduction/quick-start.mdx

Resolves customer-reported issue #507.

Fix broken link in quick-start.mdx

---

ingestion/source-connectors/zendesk.mdx
mint.json
snippets/general-shared-text/zendesk-cli-api.mdx
snippets/general-shared-text/zendesk.mdx
snippets/sc-shared-text/zendesk-cli-api.mdx
snippets/source_connectors/zendesk.sh.mdx
snippets/source_connectors/zendesk.v2.py.mdx

See https://unstructured-53-docs-188-zendesk-source-ingest.mintlify.app/ingestion/source-connectors/zendesk

Ingest v2: Zendesk source connector

---

snippets/general-shared-text/jira.mdx
snippets/general-shared-text/zendesk.mdx

See: 
- https://unstructured-53-video-links-2025-03-11.mintlify.app/ingestion/source-connectors/jira
- https://unstructured-53-video-links-2025-03-11.mintlify.app/ingestion/source-connectors/zendesk

Video how-to links for Jira and Zendesk connectors

---

examplecode/tools/mcp.mdx
mint.json

See https://unstructured-53-mcp-demo-2025-03-12.mintlify.app/examplecode/tools/mcp

[WIP] MCP hands-on walkthrough

---

ui/enriching/image-descriptions.mdx
ui/enriching/ner.mdx
ui/enriching/overview.mdx
ui/enriching/table-descriptions.mdx
ui/enriching/table-to-html.mdx
ui/workflows.mdx

The UI now uses buttons to select the enrichment type instead of a drop-down list.

UI: Enrichment nodes - new UI experience

---

snippets/general-shared-text/databricks-delta-table-api-placeholders.mdx
snippets/general-shared-text/databricks-delta-table-cli-api.mdx
snippets/general-shared-text/databricks-delta-table-platform.mdx
snippets/general-shared-text/databricks-delta-table.mdx

Now available in production. 
See the following (search for "unstructuredautocreated" to quickly jump to related content on each of these pages):
- Ingest: https://unstructured-53-docs-237-databricks-delta-tables.mintlify.app/ingestion/destination-connectors/databricks-delta-table
- UI: https://unstructured-53-docs-237-databricks-delta-tables.mintlify.app/ui/destinations/databricks-delta-table
- API: https://unstructured-53-docs-237-databricks-delta-tables.mintlify.app/api-reference/workflow/destinations/databricks-delta-table

Ingest/UI/API: Delta Tables in Databricks destination connector - automatic table creation

---

docs.json

Add Google Tag Manager support

---

docs.json

See left-hand TOC when viewing https://unstructured-53-org-accts-toc-2025-04-14.mintlify.app/ui/account/overview

Update TOC for multi-user accounts

---

snippets/general-shared-text/ibm-watsonxdata.mdx

See for example https://unstructured-53-docs-232-ibm-watsonxdata.mintlify.app/ui/destinations/ibm-watsonxdata

IBM watsonx.data connector: add links to how-to videos

---

docs.json
ingestion/source-connectors/discord.mdx
snippets/general-shared-text/discord-cli-api.mdx
snippets/general-shared-text/discord.mdx
snippets/sc-shared-text/discord-cli-api.mdx
snippets/source_connectors/discord.sh.mdx
snippets/source_connectors/discord.v2.py.mdx

See https://unstructured-53-docs-251-discord.mintlify.app/ingestion/source-connectors/discord

Ingest: Discord source connector

---

ui/enriching/ner.mdx
ui/workflows.mdx

See additions to https://unstructured-53-docs-253-ner-re.mintlify.app/ui/enriching/ner

Entity relationships added to NER

---

docs.json

Not sure how this one snuck in there...

Remove infinite redirect

---

snippets/quickstarts/platform.mdx
ui/workflows.mdx

See for example Step 4, Item 8, of https://unstructured-53-reprocess-all-2025-04-17.mintlify.app/ui/quickstart#remote-quickstart

Correct and clarify Reprocess All checkbox behavior

---

ui/document-elements.mdx

See https://unstructured-53-ontology-to-elements-2025-04-23.mintlify.app/ui/document-elements

Unstructured element ontology and HTML-element mapping, plus links to latest element and metadata listings in source

---

examplecode/notebooks.mdx

See https://unstructured-53-snowflake-notebook-2025-05-05.mintlify.app/examplecode/notebooks

Link to demo notebook for using Unstructured with Snowflake Cortex for RAG Search

---

ui/document-elements.mdx

See https://unstructured-53-connector-metadata-2025-05-05.mintlify.app/ui/document-elements#additional-metadata-fields-by-connector-type-within-record-locator

Additional metadata fields by connector type (within record_location)

---

api-reference/partition/overview.mdx
api-reference/troubleshooting/api-key-url.mdx
snippets/general-shared-text/first-time-api-destination-connector.mdx
snippets/general-shared-text/first-time-api-source-connector.mdx
snippets/general-shared-text/first-time-ui-destination-connector.mdx
snippets/general-shared-text/first-time-ui-source-connector.mdx
snippets/general-shared-text/get-started-simple-api-only.mdx
snippets/general-shared-text/get-started-simple-ui-only.mdx
ui/account/billing.mdx

Coordinate with related feature release into production. 
For examples, see:
- https://unstructured-53-saas-signup-2025-05-06.mintlify.app/welcome#unstructured-ui-quickstart -> "Step 1: Sign up and sign in"
- https://unstructured-53-saas-signup-2025-05-06.mintlify.app/welcome#unstructured-workflow-endpoint-quickstart -> "Step 1: Sign up, sign in, and get your API key"

[Hold] SaaS signup guidance

---

api-reference/workflow/overview.mdx
examplecode/codesamples/api/Unstructured-REST-API-Workflow-Endpoint.postman_collection.json

See discussion of the Postman collection in https://unstructured-53-postman-2025-05-07.mintlify.app/api-reference/workflow/overview#curl-and-postman
If you try to test this out end-to-end now, note that importing this collection into Postman will not work until this PR is merged, as the collection will not yet have made it to the main branch before the merge is completed.

Add Postman collection for Workflow Endpoint

---

snippets/general-shared-text/dropbox.mdx

See second of two videos, and `curl` command, in: https://unstructured-53-dropbox-refresh-token-2025-05-16.mintlify.app/ui/sources/dropbox

Dropbox source connector: add video link for refresh tokens; update curl command example for refresh tokens

---

open-source/installation/docker-installation.mdx
open-source/installation/full-installation.mdx

See: 
- Full local installation instructions: https://unstructured-53-open-source-full-install-2025-05-21.mintlify.app/open-source/installation/full-installation
- Docker installation instructions: https://unstructured-53-open-source-full-install-2025-05-21.mintlify.app/open-source/installation/docker-installation

Open source installation steps: update full local installation and Docker installation instructions

---

docs.json
examplecode/tools/crewai.mdx
examplecode/tools/mcp-partition.mdx
examplecode/tools/mcp.mdx

See https://unstructured-53-crew-ai-demo.mintlify.app/examplecode/tools/crewai

CrewAI multi-agent demo walkthrough

---

snippets/general-shared-text/supported-file-types-platform.mdx

Sync'ing this list with the latest validation report from Engineering.

UI/API: update supported file types

---

docs.json

Try the "Open in ChatGPT" and/or "Open in Claude" from any page, starting from https://unstructured-53-ai-tools-2025-06-24.mintlify.app/welcome

AI tools: enable chat with ChatGPT and Claude from doc pages

---

api-reference/workflow/jobs.mdx
api-reference/workflow/overview.mdx

See:
- https://unstructured-53-jobs-details-fails-2025-06-17.mintlify.app/api-reference/workflow/overview#get-processing-details-for-a-job
- https://unstructured-53-jobs-details-fails-2025-06-17.mintlify.app/api-reference/workflow/overview#get-failed-file-details-for-a-job

Workflow Endpoint: get job details, get failed files for job

---

docs.json
examplecode/tools/sharepoint-events.mdx

See https://unstructured-53-sharepoint-events-2025-07-10.mintlify.app/examplecode/tools/sharepoint-events

SharePoint source connector: workflow run trigger

---

docs.json
snippets/general-shared-text/new-document.mdx

To try it, go to https://unstructured-53-feedback-form-2025-07-15.mintlify.app/welcome and then, in the left navigation sidebar, click the **Feedback** (pencil) icon.

New feedback form

---

docs.json
examplecode/tools/databricks-volumes-events.mdx

See https://unstructured-53-databricks-volumes-trigger-2025-07-15.mintlify.app/examplecode/tools/databricks-volumes-events

Databricks Volumes source connector: workflow run trigger

---

api-reference/workflow/destinations/s3.mdx
api-reference/workflow/sources/s3.mdx
open-source/ingestion/destination-connectors/s3.mdx
open-source/ingestion/source-connectors/s3.mdx
snippets/general-shared-text/s3-metadata.mdx
ui/destinations/s3.mdx
ui/sources/s3.mdx

See for example https://unstructured-53-s3-metadata-2025-07-29.mintlify.app/ui/sources/s3#work-with-user-defined-metadata
(Also, rearranged the content across all of the S3-related connector docs to group related how-to content together more closely.)

S3 source connectors: how to work with user-defined metadata

---

examplecode/notebooks.mdx

See the first (top left) tile in https://unstructured-53-mlk-notebook-2025-08-01.mintlify.app/examplecode/notebooks

Adding MLK notebook to notebooks gallery

---

snippets/general-shared-text/delta-table.mdx
snippets/general-shared-text/s3-operation-latency.mdx
snippets/general-shared-text/s3.mdx

S3-based connectors: S3 operation latency warning note

---

api-reference/partition/sdk-python.mdx
api-reference/workflow/retries.mdx
docs.json

See:
- Workflow Endpoint: https://unstructured-53-python-sdk-retries-2025-08-12.mintlify.app/api-reference/workflow/retries
- Partition Endpoint: https://unstructured-53-python-sdk-retries-2025-08-12.mintlify.app/api-reference/partition/sdk-python#retries

Unstructured API: Retries for Workflow and Partition Endpoints

---

api-reference/workflow/destinations/s3.mdx
api-reference/workflow/sources/s3.mdx
snippets/general-shared-text/s3-ambient-creds.mdx
ui/destinations/s3.mdx
ui/sources/s3.mdx

See for example https://unstructured-53-doc-28-s3-ambient-creds.mintlify.app/ui/sources/s3#fips-and-ambient-credentials

S3 connectors: UI and Workflow Endpoint - how to specify a FIPS bucket and use ambient credentials

---

enterprise/overview.mdx
faq/faq.mdx
snippets/general-shared-text/first-time-api-destination-connector.mdx
snippets/general-shared-text/first-time-api-source-connector.mdx
snippets/general-shared-text/first-time-ui-destination-connector.mdx
snippets/general-shared-text/first-time-ui-source-connector.mdx
snippets/general-shared-text/get-started-simple-api-only.mdx
snippets/general-shared-text/get-started-simple-ui-only.mdx
snippets/general-shared-text/sharepoint.mdx
welcome.mdx

!!! COORDINATE WITH STEF BEFORE MERGING !!!
See for example:
- Step 1 of https://unstructured-53-doc-32-launch.mintlify.app/welcome#unstructured-ui-quickstart
- Step 1 of https://unstructured-53-doc-32-launch.mintlify.app/welcome#unstructured-api-quickstart

Unstructured product info site launch: minor URL updates

---

examplecode/notebooks.mdx

DO NOT MERGE until https://github.com/Unstructured-IO/notebooks/pull/14 has been merged first.

Update example notebook URLs to point to GitHub

---

ui/walkthrough.mdx

Adding tips throughout to:
- Increase readers' overall product knowledge
- Describe features and UI settings that are not fully covered in the main walkthrough's steps
- Understand some unexpected side effects when running the steps
- Understand when and why to choose some particular settings and approaches over others
See the green "tip" boxes scattered throughout https://unstructured-53-walkthrough-2025-09-25.mintlify.app/ui/walkthrough

UI walkthrough: add tips
