Unstructured-IO/docs

open-source/ingest/source-connectors/overview.mdx, open-source/ingest/source-connectors/wikipedia.mdx
The PR adds a mention on how to proceed with the *.json files generated as a result of ingesting data from a source connector. 
Also, fixes a typo.
=> elements_from_json tip for the source connectors docs

open-source/introduction/overview.mdx
updating a URL but seems like an earlier change wasn't merged and this is re-adding at the bottom:
* Traditional ETL
=> Update overview.mdx with correct embedding section url

api-reference/api-services/free-api.mdx, api-reference/api-services/saas-api-development-guide.mdx
To avoid confusion, the file path in the examples is now a placeholder - PATH_TO_FILE
=> Replaced file path in quick start API guides with a placeholder PATH_TO_FILE

mint.json
The link was requiring @unstructured.io email. Replaced with the Slack link from the website
=> Fixed the Community link leading to Slack

open-source/concepts/models.mdx
Updates the docs to remove the Chipper reference from the OSS section since Chipper is only supported in the API and Platform.
=> docs: remove chipper oss reference

open-source/core-functionality/cleaning.mdx
Hi, We need to fix the example code for clean_ordered_bullets
If you look at this link
https://docs.unstructured.io/open-source/core-functionality/cleaning#clean-ordered-bullets
`
from unstructured.cleaners.core import clean_ordered_bullets 
clean_bullets("1.1 This is a very important point")
clean_bullets("a.b This is a very important point ●")
`
Correction:
`
from unstructured.cleaners.core import clean_ordered_bullets
**clean_ordered_bullets**("1.1 This is a very important point")
**clean_ordered_bullets**("a.b This is a very important point ●")
`
=> fix: correct use of clean_ordered_bullets function cleaning.mdx

open-source/concepts/models.mdx
Removes the section on bringing your own layout parser model, which is no longer supported in `unstructured-inference` as of this PR: https://github.com/Unstructured-IO/unstructured-inference/pull/350
=> docs: layoutparser models are no longer supported

api-reference/api-services/sdk.mdx
The args to RetryConfig were misplaced. Up next: I'll come back in here and document the available options for the RetryConfig.
Related: https://github.com/Unstructured-IO/unstructured/issues/3172
=> Fix python RetryConfig example

api-reference/api-services/sdk.mdx
To coincide with:
https://github.com/Unstructured-IO/unstructured-js-client/pull/84
https://github.com/Unstructured-IO/unstructured-python-client/pull/118
* Note that the param is true by default
* Add more explicit instructions for chunking when a pdf has been split
=> Update sdk docs for page splitting defaulting to true

open-source/installation/full-installation.mdx
- Cleans up old installation instructions for `conda` on Windows which are not officially supported.
- Adds notes on system dependencies to the "full installation" section.
=> docs: cleanup oss installation instructions

api-reference/api-services/sdk.mdx
Default is being updated:
https://github.com/Unstructured-IO/unstructured-python-client/pull/122
https://github.com/Unstructured-IO/unstructured-js-client/pull/87
=> Bump default split page concurrency level in SDKs

mint.json, welcome.mdx
I'd changed the top level API in the nav to Serverless API and it was confusing. I've also better explained this situation on the welcome page.
=> Fixed some api titling and welcome page confusion

api-reference/api-services/chunking.mdx, api-reference/api-services/overview.mdx, api-reference/best-practices/chunking.mdx, mint.json, open-source/best-practices/chunking.mdx, open-source/core-functionality/chunking.mdx, platform/overview.mdx, welcome.mdx
A few spots where this shows up:
- API TOC sidebar (may need to scroll down, look for "Best Practices"): https://unstructured-53-best-practices-2024-07-19.mintlify.app/api-reference/api-services/overview
- OSS TOC sidebar (may need to scroll down, look for "Best Practices"): https://unstructured-53-best-practices-2024-07-19.mintlify.app/open-source/introduction/overview
- "Learn more" in these spots:
- https://unstructured-53-best-practices-2024-07-19.mintlify.app/api-reference/api-services/chunking#learn-more
- https://unstructured-53-best-practices-2024-07-19.mintlify.app/open-source/core-functionality/chunking#learn-more
Feel free to suggest other spots to link to these. 😄
=> Add links to blogs, best practices TOCs

api-reference/how-to/extract-image-block-types.mdx, api-reference/how-to/text-as-html.mdx, mint.json, snippets/how-to-api/extract_text_as_html.py.mdx
A code example I wrote that shows how to use the Unstructured Python SDK to extract, save, and show `text_as_html` elements.
See: https://unstructured-53-text-as-html-2024-07-23.mintlify.app/api-reference/how-to/text-as-html
=> How to extract text_as_html

ingestion/overview.mdx
We really don't have a centralized place in the docs that covers the Ingest CLI all by itself or Ingest Python all by itself. It seems to make sense to put this in the Ingestion overview doc.
See https://unstructured-53-ingest-cli-python-overview-2024-07-29.mintlify.app/ingestion/overview
=> Add info to ingestion overview about the Ingest CLI and Ingest Python

api-reference/api-services/free-api.mdx, api-reference/api-services/partition-via-api.mdx, api-reference/api-services/post-requests.mdx, api-reference/api-services/saas-api-development-guide.mdx, api-reference/api-services/sdk.mdx
Until this PR, our main quickstarts and overviews for the CLI, SDKs, and open source library didn't show how to print or write the processed data that is returned. This would result in running code and nothing appearing to happen, or at best perhaps only the first element is printed to the terminal. This PR now prints all of the results and also saves the results locally for these quickstarts and overviews, enabling customers to get a better understanding of the shape of their processed data. 
See: 
- https://unstructured-53-quickstart-updates-2024-07-29.mintlify.app/api-reference/api-services/saas-api-development-guide
- https://unstructured-53-quickstart-updates-2024-07-29.mintlify.app/api-reference/api-services/free-api
- https://unstructured-53-quickstart-updates-2024-07-29.mintlify.ap …
=> Quickstarts and overviews: show how to print and write data

api-reference/api-services/examples.mdx, api-reference/api-services/free-api.mdx, api-reference/api-services/partition-via-api.mdx, api-reference/api-services/saas-api-development-guide.mdx, api-reference/api-services/sdk.mdx, snippets/general-shared-text/api-key-url.mdx, snippets/general-shared-text/no-url-for-serverless-api.mdx, welcome.mdx
New behavior, per @awalker4 @amanda103. 
You do not need to specify API URL when using Serverless API (the default). You must in all other cases.
=> Must specify API URL when using POST, Free, Azure, and AWS calling patterns

api-reference/api-services/free-api.mdx, api-reference/api-services/overview.mdx, api-reference/api-services/partition-via-api.mdx, api-reference/api-services/post-requests.mdx, api-reference/api-services/saas-api-development-guide.mdx, api-reference/api-services/sdk-jsts.mdx, api-reference/api-services/sdk-python.mdx, api-reference/ingest/python-ingest.mdx, ingestion/overview.mdx, open-source/introduction/overview.mdx, snippets/concepts/document-elements.mdx, welcome.mdx
The sizes of notes were starting to get a bit large, especially in the introductory content. This PR seeks to reduce that a bit to make for a bit cleaner and less intimidating experience.
Also, for customers who might "parachute" directly into the single-file how-to docs, added broef notes/links to where to go find out about multi-file options. 
Docs with the most updates here:
- https://unstructured-53-naming-cleanup-2024-07-31.mintlify.app/api-reference/api-services/saas-api-development-guide
- https://unstructured-53-naming-cleanup-2024-07-31.mintlify.app/api-reference/api-services/free-api
- https://unstructured-53-naming-cleanup-2024-07-31.mintlify.app/api-reference/api-services/sdk-python
- https://unstructured-53-naming-cleanup-2024-07-31.mintlify.app/api-reference/api-services/sdk- …
=> Reduce sizes of notes in introductory content, more clarity on single/multi-file options, etc.

snippets/ingest-configuration-shared/chunking-configuration.mdx, snippets/ingest-configuration-shared/embedding-configuration.mdx, snippets/ingest-configuration-shared/fsspec-configuration.mdx, snippets/ingest-configuration-shared/overview.mdx, snippets/ingest-configuration-shared/partition-configuration.mdx, snippets/ingest-configuration-shared/permissions-configuration.mdx, snippets/ingest-configuration-shared/processor-configuration.mdx
See: 
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/overview
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/processor-configuration
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/read-configuration
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/partition-configuration
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/permissions-configuration
- https://unstructured-53-docs-37-ingest-configs.mintlify.app/api-reference/ingest/ingest-configuration/retry-strategy-configuration
- …
=> Add missing ingest connector configuration parameter descriptions

api-reference/api-services/aws.mdx, api-reference/api-services/azure.mdx, snippets/how-to-api/azure-aws.mdx
Until now, we had only a POST example for Azure and AWS. This PR adds examples for the Python SDK, the JS/TS SDK, the Ingest CLI, the Ingest Python library, and the open source library.
See the following - note that it's the same content for both!
- Azure: https://unstructured-53-azure-aws-examples-2024-08-02.mintlify.app/api-reference/api-services/azure (scroll to the very bottom/end)
- AWS: https://unstructured-53-azure-aws-examples-2024-08-02.mintlify.app/api-reference/api-services/aws (scroll to the very bottom/end)
=> Azure and AWS: add full list of code examples for SDKs, ingest CLI and library, and open source

api-reference/ingest/destination-connector/mongodb.mdx, api-reference/ingest/source-connectors/mongodb.mdx, open-source/ingest/destination-connectors/mongodb.mdx, open-source/ingest/source-connectors/mongodb.mdx, snippets/dc-shared-text/mongodb.mdx, snippets/destination_connectors/mongodb.sh.mdx, snippets/destination_connectors/mongodb.v1.py.mdx, snippets/destination_connectors/mongodb.v2.py.mdx, snippets/general-shared-text/mongodb.mdx, snippets/sc-shared-text/mongodb.mdx, snippets/source_connectors/mongodb.sh.mdx, snippets/source_connectors/mongodb.v1.py.mdx
See:
- API: https://unstructured-53-docs-36-mongodb.mintlify.app/api-reference/ingest/destination-connector/mongodb
- Open source: https://unstructured-53-docs-36-mongodb.mintlify.app/open-source/ingest/destination-connectors/mongodb
For comparison, here are the source connector docs:
- API: https://unstructured-53-docs-36-mongodb.mintlify.app/api-reference/ingest/source-connectors/mongodb
- Open source: https://unstructured-53-docs-36-mongodb.mintlify.app/open-source/ingest/source-connectors/mongodb
=> MongoDB v2 destination connector (no v2 source connector available yet)

api-reference/api-services/examples.mdx, api-reference/api-services/free-api.mdx, welcome.mdx
Also, use `server` parameter to set `free-api` instead of `server_url` (Python) or `serverURL` (JS/TS). 
For the Python SDK only, the API key parameter is named `api_key_auth`.
=> Unstructured SDKs: when using the Free API, you can now use the short string 'free-api' instead of the URL

api-reference/api-services/aws.mdx, api-reference/api-services/azure.mdx, api-reference/api-services/free-api.mdx, api-reference/api-services/saas-api-development-guide.mdx, examplecode/codesamples/apioss/table-extraction-from-pdf.mdx, ingestion/overview.mdx, open-source/concepts/models.mdx, open-source/core-functionality/partitioning.mdx, open-source/core-functionality/staging.mdx, open-source/installation/docker-installation.mdx, open-source/introduction/quick-start.mdx, openapi.json, snippets/destination_connectors/sql.sh.mdx, snippets/destination_connectors/sql.v1.py.mdx, snippets/how-to-api/extract_image_block_types.py.mdx, snippets/how-to-api/extract_text_as_html.py.mdx, snippets/how-to-oss/set_ocr_agent.py.mdx, snippets/ingest-configuration-shared/overview.mdx, snippets/quickstarts/platform.mdx, welcome.mdx
These GitHub paths will be going away in the next few releases: https://github.com/Unstructured-IO/unstructured/tree/main/example-docs and https://github.com/Unstructured-IO/unstructured/tree/main/unstructured/ingest
Proactively updating these paths now to the new GitHub paths, which also work now: https://github.com/Unstructured-IO/unstructured-ingest/tree/main/example-docs and https://github.com/Unstructured-IO/unstructured-ingest/tree/main/unstructured_ingest
Also, many paths in the examples to `example-docs` did not use the same folder path structure (i.e. `examples-docs/DA-1p.pdf` instead of `example-docs/pdf/DA-1p.pdf`, which could make these examples slightly more difficult to locate in their original sources. I updated these for clarity.
=> Fix paths unstructured -> unstructured-ingest

api-reference/ingest/ingest-cli.mdx, api-reference/ingest/ingest-dependencies.mdx, api-reference/ingest/python-ingest.mdx, ingestion/overview.mdx, mint.json, snippets/general-shared-text/astradb-cli-api.mdx, snippets/general-shared-text/azure-cli-api.mdx, snippets/general-shared-text/box-cli-api.mdx, snippets/general-shared-text/couchbase-cli-api.mdx, snippets/general-shared-text/dropbox-cli-api.mdx, snippets/general-shared-text/google-drive-cli-api.mdx, snippets/general-shared-text/ingest-dependencies.mdx, snippets/general-shared-text/mongodb-cli-api.mdx, snippets/general-shared-text/opensearch-cli-api.mdx, snippets/general-shared-text/s3-cli-api.mdx, snippets/general-shared-text/singlestore-cli-api.mdx, snippets/general-shared-text/sql-cli-api.mdx, snippets/general-shared-text/weaviate-cli-api.mdx, welcome.mdx
This PR attempts to help educate customers about scenarios in which proactively installing dependency extras are needed. 
See https://unstructured-53-install-extras-2024-08-13.mintlify.app/api-reference/ingest/ingest-dependencies
=> Additional ingest dependency extras

api-reference/api-services/accessing-unstructured-api.mdx, api-reference/api-services/api-parameters.mdx, api-reference/api-services/aws.mdx, api-reference/api-services/azure.mdx, api-reference/api-services/free-api.mdx, api-reference/api-services/partition-via-api.mdx, api-reference/api-services/post-requests.mdx, api-reference/api-services/saas-api-development-guide.mdx, api-reference/api-services/sdk-jsts.mdx, api-reference/api-services/sdk-python.mdx, snippets/general-shared-text/use-ingest-instead.mdx, snippets/how-to-api/azure-aws.mdx, snippets/ingestion/local-to-local.v2.py.mdx, welcome.mdx
Ingest is faster for larger individual files--and better at handling multiple files at a time in batches--than POST requests, the SDKs, or the open-source library. As such, this PR seeks to emphasize the Ingest CLI and Ingest Python library, and de-emphasize POST requests, the SDKs, and the open-source library (although the docs for these are still there). See:
- Welcome page's quickstarts: https://unstructured-53-docs-56-ingest.mintlify.app/welcome#quickstart-unstructured-serverless-api
- Unstructured Serverless API page's quickstarts: https://unstructured-53-docs-56-ingest.mintlify.app/api-reference/api-services/saas-api-development-guide#quickstart
- Free Unstructured API page's quickstarts: https://unstructured-53-docs-56-ingest.mintlify.app/api-reference/api-services/free-api#quicksta …
=> Emphasize Ingest over POST, SDKs, and open source

api-reference/best-practices/speed-up-large-files-batches.mdx, api-reference/how-to/extract-image-block-types.mdx, api-reference/how-to/get-chunked-elements.mdx, api-reference/how-to/get-elements.mdx, api-reference/how-to/text-as-html.mdx, snippets/how-to-api/extract_image_block_types_ingest.py.mdx, snippets/how-to-api/extract_text_as_html_ingest.py.mdx, snippets/how-to-api/get_chunked_elements.py.mdx, snippets/how-to-api/get_chunked_elements_ingest.py.mdx
Added Ingest post-processing examples for how-to:
- Get elements: https://unstructured-53-docs-57-ingest.mintlify.app/api-reference/how-to/get-elements
- Get tables as HTML: https://unstructured-53-docs-57-ingest.mintlify.app/api-reference/how-to/text-as-html
- Get images and tables from documents: https://unstructured-53-docs-57-ingest.mintlify.app/api-reference/how-to/extract-image-block-types
- Get chunked elements: https://unstructured-53-docs-57-ingest.mintlify.app/api-reference/how-to/get-chunked-elements
=> Emphasize Ingest in how-to's and best practices

snippets/destination_connectors/pinecone.sh.mdx, snippets/destination_connectors/pinecone.v1.py.mdx, snippets/destination_connectors/pinecone.v2.py.mdx, snippets/general-shared-text/pinecone-cli-api.mdx
Related:
- https://github.com/Unstructured-IO/unstructured-ingest/issues/25
- https://github.com/Unstructured-IO/unstructured-ingest/pull/30
=> Pinecone: envrionment name no longer required (nor works)

welcome.mdx
See the 2nd card from the top, titled "Unstructured Serverless API services:" https://unstructured-53-emphasize-ingest-welcome-2024-08-21.mintlify.app/welcome#product-offerings
=> Remove mention of non-Ingest tools from the welcome page

api-reference/api-services/examples.mdx, api-reference/api-services/partition-via-api.mdx, api-reference/api-services/sdk-jsts.mdx, api-reference/api-services/sdk-python.mdx, api-reference/how-to/get-elements.mdx, snippets/how-to-api/extract_image_block_types.py.mdx, snippets/how-to-api/extract_text_as_html.py.mdx, snippets/how-to-api/get_chunked_elements.py.mdx, snippets/how-to-api/get_chunked_elements_ingest.py.mdx
Printing out all of the elements can sometimes crash some notebooks. 
In some cases, the point of a particular code example is about how to get elements. In these cases, just print out the first element only, or save the results to a file for later examination. 
See:
- https://unstructured-53-docs-62-print-elements.mintlify.app/api-reference/api-services/examples - Revised the Python SDK and JS/TS SDK examples
- https://unstructured-53-docs-62-print-elements.mintlify.app/api-reference/api-services/partition-via-api#basics
- https://unstructured-53-docs-62-print-elements.mintlify.app/api-reference/api-services/sdk-jsts#basics
- https://unstructured-53-docs-62-print-elements.mintlify.app/api-reference/api-services/sdk-python#basics
- …
=> Revise code example to not show printing out all elements

snippets/ingest-configuration-shared/chunking-configuration.mdx, snippets/ingest-configuration-shared/partition-configuration.mdx, snippets/ingest-configuration-shared/processor-configuration.mdx
Also clarified similar `partition_by_api`, `api_key`, and `partition_endpoint`.
See: 
- API: https://unstructured-53-chunk-by-api-2024-09-06.mintlify.app/api-reference/ingest/ingest-configuration/chunking-configuration
- Open source: https://unstructured-53-chunk-by-api-2024-09-06.mintlify.app/open-source/ingest/ingest-configuration/chunking-configuration
=> Chunking API: Added missing descriptions for chunk_by_api, chunk_api_key, and chunking_endpoint

mint.json, platform/connectors.mdx, platform/overview.mdx, platform/platform-destination-connectors/overview.mdx, platform/platform-destination-connectors/s3.mdx, platform/platform-source-connectors/azure-blob-storage.mdx, platform/platform-source-connectors/overview.mdx, platform/platform-source-connectors/s3.mdx, platform/supported-file-types.mdx, snippets/quickstarts/platform.mdx
See:
- Supported file types in Platform: https://unstructured-53-platform-2024-09-06.mintlify.app/platform/supported-file-types
- Supported connector types in Platform: https://unstructured-53-platform-2024-09-06.mintlify.app/platform/connectors
- Added list of supported source connectors in Platform to Platform source connectors overview: https://unstructured-53-platform-2024-09-06.mintlify.app/platform/platform-source-connectors/overview
- Added list of supported destination connectors in Platform to Platform destination connectors overview: https://unstructured-53-platform-2024-09-06.mintlify.app/platform/platform-destination-connectors/overview
- Minor cleanup of some page titles to match UI (i.e. "Amazon S3" -> "S3")
Also:
- Added missing "Enrich" step to Platform pipeline flow …
=> Unstructured Platform: add lists of supported files types, connector types

api-reference/api-services/examples.mdx, api-reference/api-services/post-requests.mdx, examplecode/codesamples/apioss/table-extraction-from-pdf.mdx, faq/faq.mdx
Removed these params:
```
...
-F 'split-pdf-page=true' \
-F 'split-pdf-allow-failed=true' \
-F 'split-pdf-concurrency-level=15' \
...
```
With `curl`, these parameters tell the server "I want you to split the doc," which we do not support. `curl` itself is the client, and does not split a doc itself.
=> curl example fixes: remove split-on-server params

mint.json, platform/document-elements.mdx, platform/partitioning.mdx
We have these in the API and open-source library sections, but they have lots of API- and code-focused content. This PR attempts to present this content from a Platform-centric perspective. 
See: 
- https://unstructured-53-docs-64-platform-partitioning.mintlify.app/platform/document-elements
- https://unstructured-53-docs-64-platform-partitioning.mintlify.app/platform/partitioning
=> Platform docs: element and partitioning concepts from a Platform perspective

snippets/destination_connectors/azure.sh.mdx, snippets/destination_connectors/azure.v1.py.mdx, snippets/destination_connectors/azure.v2.py.mdx, snippets/general-shared-text/azure-cli-api.mdx, snippets/general-shared-text/azure-platform.mdx, snippets/general-shared-text/azure.mdx, snippets/source_connectors/azure.sh.mdx, snippets/source_connectors/azure.v1.py.mdx, snippets/source_connectors/azure.v2.py.mdx
Azure Storage remote URLs that start with `abfs://` work under some circumstances, but `az://` seems to work under all circumstances during my testing. I confirmed this with Engineering. 
Also, for consistency, changed `AZURE_STORAGE_ACCOUNT_URL` to `AZURE_STORAGE_REMOTE_URL` to more closely match related parameter names.
See:
- Platform: 
- Source: https://unstructured-53-azure-2024-09-11.mintlify.app/platform/platform-source-connectors/azure-blob-storage
- API: 
- Source: https://unstructured-53-azure-2024-09-11.mintlify.app/api-reference/ingest/source-connectors/azure
- Destination: https://unstructured-53-azure-2024-09-11.mintlify.app/api-reference/ingest/destination-connector/azure
- Open source:
- Source: https://unstructured-53-azure-2024-09-11.mintlify.app/open-source/ingest/source …
=> Azure source connector: fix path abfs -> az

snippets/general-shared-text/use-ingest-instead.mdx
See for instance:
- https://unstructured-53-use-ingest-2024-09-13.mintlify.app/api-reference/api-services/accessing-unstructured-api
- https://unstructured-53-use-ingest-2024-09-13.mintlify.app/api-reference/api-services/sdk-python
- https://unstructured-53-use-ingest-2024-09-13.mintlify.app/api-reference/api-services/sdk-jsts
- https://unstructured-53-use-ingest-2024-09-13.mintlify.app/api-reference/api-services/post-requests
- https://unstructured-53-use-ingest-2024-09-13.mintlify.app/api-reference/api-services/partition-via-api
(Prompted by https://github.com/Unstructured-IO/unstructured-python-client/issues/171)
=> Change 'use Ingest instead' recommendation from caution to informative note

api-reference/how-to/embedding.mdx, open-source/core-functionality/embedding.mdx, open-source/introduction/overview.mdx
As such, I updated the embedding page in the Unstructured open-source library docs to indicate that this built-in functionality is no longer available. I also point to alternatives such as the Unstructured Ingest CLI and Ingest Python library, as well as provide an example Python script I wrote and successfully tested that calls Hugging Face to generate and add embeddings to an existing JSON file that is generated by calling the Unstructured open-source library.
See https://unstructured-53-embeddings-2024-09-12.mintlify.app/open-source/core-functionality/embedding
=> Built-in embedding functions removed from Unstructured open-source

snippets/general-shared-text/elasticsearch.mdx
Same video links on all of these pages. See:
Platform:
- Source: https://unstructured-53-docs-61-elasticsearch.mintlify.app/platform/platform-source-connectors/elasticsearch
- Destination: https://unstructured-53-docs-61-elasticsearch.mintlify.app/platform/platform-destination-connectors/elasticsearch
API:
- Source: https://unstructured-53-docs-61-elasticsearch.mintlify.app/api-reference/ingest/source-connectors/elastic-search
- Destination: https://unstructured-53-docs-61-elasticsearch.mintlify.app/api-reference/ingest/destination-connector/elasticsearch
Open source:
- Source: https://unstructured-53-docs-61-elasticsearch.mintlify.app/open-source/ingest/source-connectors/elastic-search
- Destination: https://unstructured-53-docs-61-elasticsearch.mintlify.app/open-source/ingest/destination …
=> Elasticsearch connectors: how-to video links

snippets/general-shared-text/opensearch.mdx
See:
- Platform:
- API:
- Open source:
=> OpenSearch connectors: how-to video links

examplecode/notebooks.mdx
1) Removed the quick start guide as it’s too old. 
2) Removed the databricks notebook - it’s old and we can’t fix it (external)
3) Moved notebooks that have not yet been updated to ingest v2 to the bottom of the page.
=> Notebooks page reorganized

api-reference/api-services/saas-api-development-guide.mdx, api-reference/ingest/overview.mdx, open-source/ingest/overview.mdx, snippets/dc-shared-text/weaviate-cli-api.mdx, snippets/ingest-configuration-shared/overview.mdx
See: 
- https://unstructured-53-videos-2024-09-23.mintlify.app/api-reference/api-services/saas-api-development-guide#set-up-billing
- https://unstructured-53-videos-2024-09-23.mintlify.app/api-reference/api-services/saas-api-development-guide#manage-your-account
- https://unstructured-53-videos-2024-09-23.mintlify.app/api-reference/ingest/overview
- https://unstructured-53-videos-2024-09-23.mintlify.app/open-source/ingest/overview
- https://unstructured-53-videos-2024-09-23.mintlify.app/api-reference/ingest/ingest-configuration/overview
- https://unstructured-53-videos-2024-09-23.mintlify.app/open-source/ingest/ingest-configuration/overview
- https://unstructured-53-videos-2024-09-23.mintlify.app/api-reference/ingest/destination-connector/weaviate
- …
=> More how-to video links: Python Ingest library, manage billing, track usage, Weaviate connector

snippets/destination_connectors/databricks_volumes.sh.mdx, snippets/destination_connectors/databricks_volumes.v1.py.mdx, snippets/destination_connectors/databricks_volumes.v2.py.mdx, snippets/general-shared-text/databricks-volumes-cli-api.mdx, snippets/general-shared-text/databricks-volumes-platform.mdx, snippets/general-shared-text/databricks-volumes.mdx
See:
- API: https://unstructured-53-docs-61-databricks-volumes.mintlify.app/api-reference/ingest/destination-connector/databricks-volumes
- Open source: https://unstructured-53-docs-61-databricks-volumes.mintlify.app/open-source/ingest/destination-connectors/databricks-volumes
=> Databricks Volumes v2 destination connector: update authentication details

api-reference/api-services/aws.mdx
See https://unstructured-53-docs-76-aws.mintlify.app/api-reference/api-services/aws
=> AWS Marketplace offering: improve how-to usability

open-source/core-functionality/partitioning.mdx
The docs refer to the partition method "above" as if it were `partition_pdf`, but it's not
=> remove incorrect info from partition_image description

platform/workflows.mdx, snippets/quickstarts/platform.mdx
We are still working on these settings. Removing these details until things are finalized.
=> Basic and advanced options

api-reference/ingest/overview.mdx, ingestion/overview.mdx, open-source/ingest/overview.mdx, snippets/ingestion/code-generator.mdx
See (same content on all pages):
- https://unstructured-53-code-builder-2024-10-10.mintlify.app/api-reference/ingest/overview#generate-python-code-examples
- https://unstructured-53-code-builder-2024-10-10.mintlify.app/open-source/ingest/overview#generate-python-code-examples
- https://unstructured-53-code-builder-2024-10-10.mintlify.app/ingestion/overview#generate-python-code-examples
=> How to use the Ingest Python code generator

api-reference/api-services/examples.mdx, api-reference/api-services/sdk-jsts.mdx, api-reference/api-services/sdk-python.mdx, api-reference/how-to/get-elements.mdx, snippets/how-to-api/extract_image_block_types.py.mdx, snippets/how-to-api/extract_text_as_html.py.mdx, snippets/how-to-api/get_chunked_elements.py.mdx
See: 
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-reference/api-services/sdk-python#async-partitioning
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-reference/api-services/sdk-jsts#processing-multiple-files
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-reference/api-services/examples#javascript-typescript-sdk (see "Python SDK" and "JavaScript/TypeScript SDK" expandable sections only)
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-reference/how-to/text-as-html (addition of "await" and "partition_async")
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-reference/how-to/extract-image-block-types (addition of "await" and "partition_async")
- https://unstructured-53-docs-77-py-sdk-async.mintlify.app/api-refe …
=> Switch SDK single-file usage examples to async multi-file

api-reference/ingest/source-connectors/astradb.mdx, open-source/ingest/source-connectors/astradb.mdx, snippets/destination_connectors/astradb.sh.mdx, snippets/destination_connectors/astradb.v1.py.mdx, snippets/destination_connectors/astradb.v2.py.mdx, snippets/general-shared-text/astradb-cli-api.mdx, snippets/source_connectors/astradb.sh.mdx, snippets/source_connectors/astradb.v1.py.mdx, snippets/source_connectors/astradb.v2.py.mdx
This PR updates the docs with a new v2 source connector snippet, plus changes namespace to keyspace in existing docs (namespace is deprecated)
=> feat: Update docs for Astra DB v2 connector updates

api-reference/api-services/aws.mdx, api-reference/api-services/azure.mdx
It's not immediately clear that these deployments will spin up a VM which needs to be managed by the user. To prevent a surprise bill, you need to shut down the VM when the API is not in use.
=> Add a warning to marketplace pages about cost prevention

mint.json, platform/connectors.mdx, platform/destinations/overview.mdx, snippets/general-shared-text/mongodb-platform.mdx, snippets/general-shared-text/mongodb.mdx
See https://unstructured-53-platform-mongodb-2024-10-18.mintlify.app/platform/destinations/mongodb
=> MongoDB destination connector for Platform

snippets/general-shared-text/postgresql.mdx, snippets/general-shared-text/sharepoint.mdx
See:
- https://unstructured-53-postgres-sharepoint-videos-2024-10-23.mintlify.app/api-reference/ingest/destination-connector/postgresql
- https://unstructured-53-postgres-sharepoint-videos-2024-10-23.mintlify.app/api-reference/ingest/source-connectors/sharepoint
=> Add embed-links to how-to videos for PostgreSQL and SharePoint

snippets/destination_connectors/postgresql.v2.py.mdx, snippets/destination_connectors/sqlite.v2.py.mdx
There were a few stray mentions to fix here.
=> Remove langchain- from embedding provider programmatic IDs

snippets/general-shared-text/airtable.mdx, snippets/general-shared-text/couchbase.mdx, snippets/general-shared-text/snowflake.mdx
See:
- Airtable: i.e. https://unstructured-53-video-embed-links-2024-10-25.mintlify.app/api-reference/ingest/source-connectors/airtable
- Couchbase: i.e. https://unstructured-53-video-embed-links-2024-10-25.mintlify.app/api-reference/ingest/source-connectors/couchbase
- Snowflake: i.e. https://unstructured-53-video-embed-links-2024-10-25.mintlify.app/api-reference/ingest/source-connectors/snowflake
=> Add third-party embed-linked how-to videos for Airtable, Couchbase, and Snowflake

api-reference/api-services/aws.mdx, api-reference/api-services/azure.mdx
Addresses a request to add "how to shut down instances" info/links to these articles.
See the top/beginning of:
- https://unstructured-53-mktplace-mgmt-2024-10-29.mintlify.app/api-reference/api-services/aws
- https://unstructured-53-mktplace-mgmt-2024-10-29.mintlify.app/api-reference/api-services/azure
=> Marketplace offerings: add links to shutdown how-to articles

snippets/general-shared-text/mongodb-cli-api.mdx, snippets/general-shared-text/mongodb-platform.mdx, snippets/general-shared-text/mongodb.mdx
Provides more clarity about what a connection string needs to look like and how to get one. 
Also, "URI" changed to "connection string."
See (same target content in all of these pages):
- https://unstructured-53-mongodb-connection-string-2024-11-05.mintlify.app/platform/destinations/mongodb
- https://unstructured-53-mongodb-connection-string-2024-11-05.mintlify.app/api-reference/ingest/source-connectors/mongodb
- https://unstructured-53-mongodb-connection-string-2024-11-05.mintlify.app/api-reference/ingest/destination-connector/mongodb
- https://unstructured-53-mongodb-connection-string-2024-11-05.mintlify.app/open-source/ingest/source-connectors/mongodb
- https://unstructured-53-mongodb-connection-string-2024-11-05.mintlify.app/open-source/ingest/destination-connectors/mongodb
=> MongoDB connectors: connection string example, how-to, and terminology

examplecode/tools/langflow.mdx
The Langflow demo mistakenly states that you can feed multiple local files into the **Unstructured** component in Langflow. You cannot. This PR corrects this statement.
See https://unstructured-53-langflow-single-file-2024-11-06.mintlify.app/examplecode/tools/langflow
=> Langflow demo: how to work with multiple files

mint.json, platform/connectors.mdx, platform/destinations/delta-table.mdx, platform/destinations/overview.mdx, snippets/general-shared-text/delta-table-platform.mdx
See https://unstructured-53-delta-table-platform-destination-2024-11-06.mintlify.app/platform/destinations/delta-table
=> Platform: Delta Table destination connector

snippets/general-shared-text/delta-table.mdx
The current Delta Table destination connector docs state that this works with Delta Tables stored in Amazon S3 buckets. But it doesn't mention how to create or set up those buckets for the correct access permissions. This PR adds this important how-to information.
See (same target content on all of these pages):
- https://unstructured-53-delta-table-s3-policy-2024-11-07.mintlify.app/platform/destinations/delta-table
- https://unstructured-53-delta-table-s3-policy-2024-11-07.mintlify.app/api-reference/ingest/destination-connector/delta-table
- https://unstructured-53-delta-table-s3-policy-2024-11-07.mintlify.app/open-source/ingest/destination-connectors/delta-table
=> Delta Table destination connector: S3 bucket creation and bucket policy scripts

mint.json, platform/connectors.mdx, platform/destinations/overview.mdx, snippets/general-shared-text/elasticsearch-platform.mdx, snippets/general-shared-text/elasticsearch.mdx
See: 
- https://unstructured-53-elasticsearch-platform-dest-conn-2024-11-14.mintlify.app/platform/destinations/elasticsearch
- https://unstructured-53-elasticsearch-platform-dest-conn-2024-11-14.mintlify.app/api-reference/ingest/source-connectors/elastic-search
- https://unstructured-53-elasticsearch-platform-dest-conn-2024-11-14.mintlify.app/api-reference/ingest/destination-connector/elasticsearch
- https://unstructured-53-elasticsearch-platform-dest-conn-2024-11-14.mintlify.app/open-source/ingest/source-connectors/elastic-search
- https://unstructured-53-elasticsearch-platform-dest-conn-2024-11-14.mintlify.app/open-source/ingest/destination-connectors/elasticsearch
=> Platform: Elasticsearch destination connector

api-reference/ingest/destination-connector/kafka.mdx, api-reference/ingest/source-connectors/kafka.mdx, open-source/ingest/destination-connectors/kafka.mdx, open-source/ingest/source-connectors/kafka.mdx, snippets/destination_connectors/kafka.sh.mdx, snippets/destination_connectors/kafka.v2.py.mdx, snippets/source_connectors/kafka.sh.mdx, snippets/source_connectors/kafka.v2.py.mdx
=> API: Kafka v2 source and destination connectors

platform/embedding.mdx, platform/overview.mdx, platform/partitioning.mdx, platform/workflows.mdx
Removing Auto and Vertex AI from Platform, per Danielle. 
Confirmed strategy fallback formulas with Danielle as well.
Combined https://github.com/Unstructured-IO/docs/pull/350 and https://github.com/Unstructured-IO/docs/pull/349 into this one. 
See:
- https://unstructured-53-platform-advanced-strategy.mintlify.app/platform/embedding
- https://unstructured-53-platform-advanced-strategy.mintlify.app/platform/overview
- https://unstructured-53-platform-advanced-strategy.mintlify.app/platform/partitioning
- https://unstructured-53-platform-advanced-strategy.mintlify.app/platform/workflows
=> Platform: Remove Auto and Vertex AI, add strategy fallback formulas

snippets/dc-shared-text/weaviate-cli-api.mdx, snippets/destination_connectors/weaviate.sh.mdx, snippets/destination_connectors/weaviate.v1.py.mdx, snippets/destination_connectors/weaviate.v2.py.mdx, snippets/general-shared-text/weaviate-cli-api.mdx, snippets/general-shared-text/weaviate.mdx
See: 
- https://unstructured-53-weaviate-api-destination-2024-11-26.mintlify.app/api-reference/ingest/destination-connector/weaviate
- https://unstructured-53-weaviate-api-destination-2024-11-26.mintlify.app/open-source/ingest/destination-connectors/weaviate
Also:
- https://unstructured-53-weaviate-api-destination-2024-11-26.mintlify.app/platform/destinations/weaviate
=> API: Weaviate v2 updates for local-, embedded-, and cloud-focused classes

platform/workflows.mdx
=> Platform: DAG options

snippets/destination_connectors/astradb.sh.mdx, snippets/destination_connectors/astradb.v1.py.mdx, snippets/destination_connectors/astradb.v2.py.mdx, snippets/general-shared-text/astradb-cli-api.mdx, snippets/general-shared-text/astradb-platform.mdx
The embedding dimensions setting was recently removed from both Platform and Ingest. This PR syncs the docs to reflect this removal.
=> Astra DB connectors: remove embedding dimensions setting from Platform, Ingest

snippets/general-shared-text/qdrant.mdx
See for example the fourth major bullet from the top/beginning of https://unstructured-53-qdrant-collection-schema-2024-12-04.mintlify.app/api-reference/ingest/destination-connector/qdrant
=> Qdrant destination connector: how to create a compatible collection

snippets/general-shared-text/onedrive-platform.mdx
For the OneDrive source connector, there's a **Path** field, which we describe in the docs. However, for the OneDrive destination connector, there is no **Path** field; instead, it's the **Remote URL** field, which we don't describe in the docs. This PR corrects this. 
See for example the very end/bottom of https://unstructured-53-onedrive-remote-url-2024-12-06.mintlify.app/platform/destinations/onedrive
=> Platform: OneDrive connector - path for source, but remote URL for destination

snippets/general-shared-text/weaviate.mdx
It seems I cannot write to a collection unless it contains at least a `record_id` property of type `text`. 
See for example the discussion in the 5th main bullet from the top/beginning of https://unstructured-53-weaviate-record-id-2024-12-05.mintlify.app/api-reference/ingest/destination-connector/weaviate
=> Weaviate destination connector: record_id property required on collections

snippets/general-shared-text/pages-billing.mdx
See for example the very end/bottom of https://unstructured-53-data-billing-2024-12-03.mintlify.app/platform/billing
=> Formula for billing non-file data as pages

snippets/general-shared-text/milvus.mdx
Until now, we've had long-form instructions that were super-generalized, leaving customers to hunt around for more details.
=> Milvus destination connector: Add docs and links for Zilliz Cloud, and Milvus on IBM Cloud watsonx.data

snippets/general-shared-text/astradb.mdx
The old video showed how to get the number of dimensions. This is no longer needed. The new video removes these instructions.
See for example: https://unstructured-53-astradb-video-link-2024-12-10.mintlify.app/platform/destinations/astradb
=> Astra DB connectors: switch out video embed link

snippets/general-shared-text/milvus.mdx
The existing Milvus setup how-to video is being replaced with a new one that is branded "Milvus on IBM watsonx.data." Also, a new video is being added to that one that is branded "Milvus on Zilliz Cloud." This is to more cleanly separate the distinct setup steps for each vendor. 
See for example https://unstructured-53-milvus-zilliz-video-2024-12-11.mintlify.app/platform/destinations/milvus
=> Milvus destination connector: update how-to video embed links

snippets/general-shared-text/sharepoint.mdx
See for example a page with the video removed: https://unstructured-53-sharepoint-video-2024-12-13.mintlify.app/platform/sources/sharepoint
=> Temporarily remove link to SharePoint video

snippets/general-shared-text/sharepoint-cli-api.mdx, snippets/general-shared-text/sharepoint-platform.mdx, snippets/general-shared-text/sharepoint.mdx
The previous instructions were buggy, conflating instructions about SharePoint app principals across tenant, root, and site collection levels. This PR more cleanly and accurately separates these scopes. 
See for example https://unstructured-53-sharepoint-app-reg-2024-12-13.mintlify.app/api-reference/ingest/source-connectors/sharepoint
=> SharePoint source connector: clean up SharePoint app principal how-to instructions

mint.json, platform/connectors.mdx, platform/sources/dropbox.mdx, platform/sources/overview.mdx, snippets/general-shared-text/dropbox-platform.mdx
This is now publicly available.
See https://unstructured-53-dropbox-platform-2024-12-12.mintlify.app/platform/sources/dropbox
=> [Hold] Platform: Dropbox source connector

mint.json, platform/connectors.mdx, platform/sources/overview.mdx, snippets/general-shared-text/google-drive-cli-api.mdx, snippets/general-shared-text/google-drive-platform.mdx, snippets/general-shared-text/google-drive.mdx
This is now publicly available.
See https://unstructured-53-google-drive-platform-2024-12-12.mintlify.app/platform/sources/google-drive
=> [Hold] Platform: Google Drive source connector

mint.json, platform/connectors.mdx, platform/sources/overview.mdx, snippets/general-shared-text/salesforce-platform.mdx, snippets/general-shared-text/salesforce.mdx
This is now publicly available.
See https://unstructured-53-salesforce-platform-2024-12-12.mintlify.app/platform/sources/salesforce
=> Platform: Salesforce source connector

mint.json, platform/connectors.mdx, platform/destinations/overview.mdx, platform/destinations/qdrant.mdx, snippets/general-shared-text/qdrant-platform.mdx, snippets/general-shared-text/qdrant.mdx
This is now publicly available.
See https://unstructured-53-qdrant-platform-2024-12-13.mintlify.app/platform/destinations/qdrant
=> Platform: Qdrant destination connector

platform/api/overview.mdx, platform/api/workflows.mdx, snippets/destination_connectors/astradb_rest_change.mdx, snippets/destination_connectors/azure_ai_search_rest_change.mdx, snippets/destination_connectors/databricks_volumes_rest_change.mdx, snippets/destination_connectors/delta_table_rest_change.mdx, snippets/destination_connectors/delta_table_rest_create.mdx, snippets/destination_connectors/elasticsearch_rest_change.mdx, snippets/destination_connectors/gcs_rest_change.mdx, snippets/destination_connectors/gcs_rest_create.mdx, snippets/destination_connectors/milvus_rest_change.mdx, snippets/destination_connectors/mongodb_rest_change.mdx, snippets/destination_connectors/onedrive_rest_change.mdx, snippets/destination_connectors/pinecone_rest_change.mdx, snippets/destination_connectors/s3_rest_change.mdx, snippets/destination_connectors/weaviate_rest_change.mdx, snippets/source_connectors/azure_rest_change.mdx, snippets/source_connectors/confluence_rest_change.mdx, snippets/source_connectors/databricks_volumes_rest_change.mdx, snippets/source_connectors/gcs_rest_change.mdx, snippets/source_connectors/mongodb_rest_change.mdx, snippets/source_connectors/onedrive_rest_change.mdx, snippets/source_connectors/outlook_rest_change.mdx, snippets/source_connectors/s3_rest_change.mdx, snippets/source_connectors/sharepoint_rest_change.mdx
There were several errors in the Platform API reference docs that I just published, now that I'm able to actually fully test the production endpoints. The biggest ones in this first follow-on PR are:
- The URL to call the API is slightly off: `https://` instead of `http://`. Switching from HTTP to HTTPS was a _relatively_ last-minute back-end update. In the meantime, our more tech-savvy customers should be able to figure this out.
- Instructions for _changing_ (_not_ creating) source and destination connectors are wrong, as `name` and `type` should not be specified. In the meantime, customers might be able to figure this out by cross-referencing the Swagger UI, but this is certainly not intuitive.
- Some of the query parameters for listing workflows are wrong. In the meantime, customers …
=> Platform API ref follow-on updates, part 1

snippets/general-shared-text/kafka-cli-api.mdx
See for example https://unstructured-53-docs-116-kafka.mintlify.app/api-reference/ingest/source-connectors/kafka
Search for "--group-id" or "group_id"
=> Kafka connectors: new group ID field

snippets/general-shared-text/couchbase-cli-api.mdx
See for example https://unstructured-53-docs-118-couchbase.mintlify.app/api-reference/ingest/source-connectors/couchbase
Search for "--collection-id" or "collection_id"
=> Couchbase source connector: new optional collection ID field

api-reference/ingest/ingest-dependencies.mdx, snippets/ingest-configuration-shared/embedding-configuration.mdx
- Uses the same extra as OpenAI (`openai`). 
- `embedding_provider` = `azure-openai`
- Default `model_name` = `text-embedding-ada-002`
See:
- https://unstructured-53-docs-119-azure-openai.mintlify.app/api-reference/ingest/ingest-dependencies - search for "Azure OpenAI"
- https://unstructured-53-docs-119-azure-openai.mintlify.app/api-reference/ingest/ingest-configuration/embedding-configuration - search for "azure-openai"
=> Add Azure OpenAI embedding provider

snippets/general-shared-text/google-drive.mdx
=> Google Drive source connector: how-to video embed link

snippets/general-shared-text/qdrant.mdx
See for example https://unstructured-53-qdrant-video-2025-01-06.mintlify.app/platform/destinations/qdrant
=> Qdrant destination connector: video how-to for setting up Qdrant Cloud

snippets/general-shared-text/dropbox.mdx
See for example https://unstructured-53-dropbox-video-2025-01-07.mintlify.app/platform/sources/dropbox
=> Dropbox connectors: how-to video link; text cleanup

examplecode/tools/langflow.mdx, examplecode/tools/vectorshift.mdx
For example, for Langflow:
And for VectorShift:
=> Tools demos: use prompt engineering to limit RAG context

api-reference/api-services/overview.mdx
Redirect users who land on the Unstructured Serverless API services overview page and are trying to find information about the Unstructured Platform API instead.
=> Unstructured Serverless API services != Unstructured Platform API

snippets/destination_connectors/box.sh.mdx, snippets/destination_connectors/box.v1.py.mdx, snippets/destination_connectors/box.v2.py.mdx, snippets/general-shared-text/box-cli-api.mdx, snippets/general-shared-text/box.mdx, snippets/source_connectors/box.sh.mdx, snippets/source_connectors/box.v1.py.mdx, snippets/source_connectors/box.v2.py.mdx
See: 
- https://unstructured-53-docs-115-box-ingest.mintlify.app/api-reference/ingest/source-connectors/box
- https://unstructured-53-docs-115-box-ingest.mintlify.app/api-reference/ingest/destination-connector/box
- https://unstructured-53-docs-115-box-ingest.mintlify.app/open-source/ingest/source-connectors/box
- https://unstructured-53-docs-115-box-ingest.mintlify.app/open-source/ingest/destination-connectors/box
=> Box connectors: now also accepts a single-line string containing the related app's private key file contents

snippets/general-shared-text/neo4j-graph.mdx
See https://unstructured-53-neo4j-queries-2025-01-17.mintlify.app/api-reference/ingest/destination-connector/neo4j#graph-output
=> Neo4j destination connector: show related query examples

snippets/general-shared-text/couchbase.mdx, snippets/general-shared-text/postgresql.mdx
Reducing some visual clutter for links, and fixing one link target.
See for example:
- https://unstructured-53-postgresql-connect-links-2025-01-21.mintlify.app/platform/sources/couchbase
- https://unstructured-53-postgresql-connect-links-2025-01-21.mintlify.app/platform/sources/postgresql
=> PostgreSQL and Couchbase connectors: fix up third-party links

snippets/general-shared-text/kafka.mdx
For now, we support only Confluent Cloud for Kafka. Other providers such as AWS and Azure offer Kafka. However, setting up authentication for those providers is very time-consuming and error-prone. Also, we have not fully tested those providers either.
See for example https://unstructured-53-kafka-cluster-types-2025-01-21.mintlify.app/api-reference/ingest/source-connectors/kafka
=> Kafka connectors: only Confluent Cloud is supported

platform/embedding.mdx, platform/workflows.mdx
Sudarshan confirmed this was released.
See: 
- https://unstructured-53-docs-136-togetherai-platform.mintlify.app/platform/embedding -> bottom/end of page
- https://unstructured-53-docs-136-togetherai-platform.mintlify.app/platform/workflows#build-it-with-me-custom -> Step 16
- https://unstructured-53-docs-136-togetherai-platform.mintlify.app/platform/workflows#embedder-node
=> Platform UI: Add TogetherAI embedding provider and models

platform/api/destinations/neo4j.mdx, platform/destinations/neo4j.mdx
Forgot to include coverage about Neo4j graph output to the Platform docs. 
See: 
- https://unstructured-53-neo4j-graph-output-2025-01-23.mintlify.app/platform/destinations/neo4j#graph-output
- https://unstructured-53-neo4j-graph-output-2025-01-23.mintlify.app/platform/api/destinations/neo4j#graph-output
=> Platform: Neo4j destination connector - add graph output coverage

platform/api/workflows.mdx
See https://unstructured-53-platform-api-workflow-schedule-2025-01-27.mintlify.app/platform/api/workflows#create-a-workflow
=> Platform API: available workflow schedule timeframe phrases

snippets/destination_connectors/databricks_delta_table_sql_based.v2.py.mdx, snippets/destination_connectors/databricks_delta_table_volume_based.v2.py.mdx
These were originally misspelled in the source code (`Databrick` instead of `Databricks`). The source code has since been fixed--so fixing it here, too.
=> Ingest v2: Delta Tables in Databricks destination connector: fixing misspelled namespaces

snippets/general-shared-text/confluence-api-placeholders.mdx, snippets/general-shared-text/confluence-cli-api.mdx, snippets/general-shared-text/confluence-platform.mdx, snippets/general-shared-text/confluence.mdx, snippets/source_connectors/confluence.sh.mdx, snippets/source_connectors/confluence.v2.py.mdx, snippets/source_connectors/confluence_rest_change.mdx, snippets/source_connectors/confluence_rest_create.mdx
See: 
- https://unstructured-53-docs-137-confluence.mintlify.app/platform/sources/confluence
- https://unstructured-53-docs-137-confluence.mintlify.app/api-reference/ingest/source-connectors/confluence
- https://unstructured-53-docs-137-confluence.mintlify.app/open-source/ingest/source-connectors/confluence
=> Confluence source connector: now accepts username/password, username/API token, or PAT for authentication

snippets/general-shared-text/onedrive.mdx
After much troubleshooting, it was discovered that you also need a SharePoint Online license to use our OneDrive connector, as OneDrive uses some SharePoint features behind the scenes.  
Also, some of the previous third-party instructions and links were a bit confusing, so this PR cleans this up a bit. 
See for example https://unstructured-53-onedrive-connector-spo-license-2025-01-29.mintlify.app/platform/sources/onedrive
=> OneDrive connector: SharePoint Online license required, also update some confusing how-to steps

snippets/general-shared-text/databricks-delta-table-api-placeholders.mdx, snippets/general-shared-text/databricks-delta-table-cli-api.mdx, snippets/general-shared-text/databricks-delta-table-platform.mdx, snippets/general-shared-text/databricks-delta-table.mdx, snippets/general-shared-text/databricks-volumes-api-placeholders.mdx, snippets/general-shared-text/databricks-volumes-platform.mdx, snippets/general-shared-text/databricks-volumes.mdx
First wave of mini-videos for Databricks. More to be added later, giving us more flexibility as our Databricks capabilities mature. Also, more details about minimum permissions were added, as there are many moving parts here.
See for example:
=> Databricks Volumes and Delta Tables connectors: Add more how-to video links, and required permissions details

snippets/general-shared-text/dropbox.mdx
See for example https://unstructured-53-docs-170-dropbox.mintlify.app/platform/sources/dropbox#replace-an-expired-access-token
=> Dropbox connectors: access tokens valid for only four hours; how to refresh expired tokens

mint.json, platform/enriching/image-descriptions.mdx, platform/enriching/ner.mdx, platform/enriching/overview.mdx, platform/enriching/table-descriptions.mdx, platform/enriching/table-to-html.mdx, platform/workflows.mdx
- Refactor the old "Summarizing" article (which didn't include table-to-HTML) into an "Enriching" TOC node with child articles for image descriptions, table descriptions, and table-to-HTML.
- Add an NER article so that internal folks who know the secret URL can access it, but hide it from the TOC for the public.  
- Also, add recently released Amazon Bedrock models "wave 2" for the VLM partitioner.
See: 
- Enrichments overview: https://unstructured-53-docs-175-ner.mintlify.app/platform/enriching/overview
- Image descriptions: https://unstructured-53-docs-175-ner.mintlify.app/platform/enriching/image-descriptions
- Table descriptions: https://unstructured-53-docs-175-ner.mintlify.app/platform/enriching/table-descriptions
- Tables to HTML: …
=> Enrichment TOC refactoring

snippets/general-shared-text/sharepoint-api-placeholders.mdx, snippets/general-shared-text/sharepoint-cli-api.mdx, snippets/general-shared-text/sharepoint-platform.mdx, snippets/general-shared-text/sharepoint.mdx, snippets/source_connectors/sharepoint.sh.mdx, snippets/source_connectors/sharepoint.v2.py.mdx, snippets/source_connectors/sharepoint_rest_change.mdx, snippets/source_connectors/sharepoint_rest_create.mdx
This is now available in Platform. (It had been made available a bit earlier in Ingest v2.)
See:
- https://unstructured-53-docs-169-sharepoint-ingest-v2.mintlify.app/platform/sources/sharepoint
- https://unstructured-53-docs-169-sharepoint-ingest-v2.mintlify.app/platform/api/sources/sharepoint
- https://unstructured-53-docs-169-sharepoint-ingest-v2.mintlify.app/api-reference/ingest/source-connectors/sharepoint
- https://unstructured-53-docs-169-sharepoint-ingest-v2.mintlify.app/open-source/ingest/source-connectors/sharepoint
=> SharePoint source connector: replace SharePoint app principals with Entra ID app registrations for authentication

mint.json, platform/enriching/overview.mdx
Reviewed by Sudarshan, et al. OK'd to publish.
See https://unstructured-53-ner-2025-02-11.mintlify.app/platform/enriching/ner
=> Platform: Add NER to TOC

snippets/general-shared-text/azure-ai-search.mdx
Before this change, the connector was not properly writing records. Confirmed through my own testing that this change fixes the issue.
=> Azure AI Search destination connector: index definition for record_id field's key - change to false

snippets/general-shared-text/weaviate-api-placeholders.mdx, snippets/general-shared-text/weaviate-cli-api.mdx, snippets/general-shared-text/weaviate-platform.mdx, snippets/general-shared-text/weaviate.mdx
This feature is now available for all users. OK'd by Shreya to publish. 
See for example https://unstructured-53-docs-190-weaviate-create-collection.mintlify.app/platform/destinations/weaviate -> the part that talks about specifying the target collection name (or not!)
=> [Hold] Weaviate destination connector: collection management behavior updates

api-reference/api-services/examples.mdx, api-reference/api-services/free-api.mdx, api-reference/api-services/saas-api-development-guide.mdx, api-reference/api-services/sdk-python.mdx, api-reference/troubleshooting/api-key-url.mdx, platform/api/overview.mdx, platform/api/workflows.mdx, snippets/general-shared-text/no-url-for-serverless-api.mdx, snippets/how-to-api/extract_image_block_types.py.mdx, snippets/how-to-api/extract_text_as_html.py.mdx, snippets/how-to-api/get_chunked_elements.py.mdx, snippets/ingestion/local-to-local.v2.py.mdx
- Removed `server_url=os.getenv("UNSTRUCTURED_API_URL")` from code examples.
- Removed old notes about `0.30.0` Python SDK behaviors.
- Removed various references to setting `UNSTRUCTURED_API_URL` to your API URL.
Etc.
=> Revert back to original API behavior for default API URLs, server_url need and placement

api-reference/how-to/choose-partitioning-strategy.mdx, platform/overview.mdx, platform/partitioning.mdx, platform/workflows.mdx, snippets/general-shared-text/platform-partitioning-strategies.mdx
Phrasing approved by Michael.
See the following (same text in all spots): 
- https://unstructured-53-docs-210-partitioning-platform.mintlify.app/platform/overview#how-does-it-work%3F -> Step 2: "Route"
- https://unstructured-53-docs-210-partitioning-platform.mintlify.app/platform/overview#how-does-it-work%3F -> All content below the blue note box.
- https://unstructured-53-docs-210-partitioning-platform.mintlify.app/platform/workflows#partitioner-node
=> Platform: Recommend using Auto partitioning strategy whenever possible

snippets/quickstarts/platform.mdx
The new how-to shows the new dynamic pipelines feature instead of the now-removed Basic, Advanced, and Platinum options.
=> Platform UI quickstart: updated video link

platform-api/api/overview.mdx, platform-api/api/workflows.mdx
To view these on an internally staged site, expand the "Python SDK (async)" sections on the following pages:
- https://unstructured-53-docs-203-python-workflow-async.mintlify.app/platform-api/api/overview
- https://unstructured-53-docs-203-python-workflow-async.mintlify.app/platform-api/api/workflows
=> Platform Workflow Endpoint: Add async code examples for all available Python SDK operations

snippets/destination_connectors/mongodb.v2.py.mdx
...but was not removed from the docs. As reported by customer in Slack
=> MongoDBUploadStagerConfig removed from Ingest v2 Python library

open-source/concepts/partitioning-strategies.mdx, platform-api/partition-api/partitioning.mdx, snippets/concepts/partitioning-strategies-oss.mdx, snippets/concepts/partitioning-strategies-platform.mdx
Open source info was accidentally showing up in Platform. This PR fixes that. 
See: 
- Open source version: https://unstructured-53-partitioning-strategies-2025-03-06.mintlify.app/open-source/concepts/partitioning-strategies
- Platform Partition Endpoint version: https://unstructured-53-partitioning-strategies-2025-03-06.mintlify.app/platform-api/partition-api/partitioning
=> Partitioning strategies: separate open source from Platform

snippets/destination_connectors/dropbox.sh.mdx, snippets/destination_connectors/dropbox.v2.py.mdx, snippets/general-shared-text/dropbox-cli-api.mdx, snippets/general-shared-text/dropbox.mdx, snippets/source_connectors/dropbox.sh.mdx, snippets/source_connectors/dropbox.v2.py.mdx
Available for Ingest v2. Not yet for Platform.
See: 
- https://unstructured-53-docs-221-dropbox-refresh-token.mintlify.app/ingestion/source-connectors/dropbox
- https://unstructured-53-docs-221-dropbox-refresh-token.mintlify.app/ingestion/destination-connectors/overview
=> Ingest v2: Dropbox connectors - enable automatic refreshing of expired access tokens

snippets/destination_connectors/astradb.sh.mdx, snippets/destination_connectors/astradb.v2.py.mdx, snippets/general-shared-text/astradb-cli-api.mdx, snippets/source_connectors/astradb.sh.mdx, snippets/source_connectors/astradb.v2.py.mdx
- For the source connector: `--fields` (CLI) and `fields` (Python).
- For the destination connector `--flatten-metadata`/`--no-flatten-metadata` (CLI) and `flatten_metadata=<True|False>` (Python).
See: 
- Source connector: https://unstructured-53-docs-220-astra-db-metadata.mintlify.app/ingestion/source-connectors/astradb
- Destination connector: https://unstructured-53-docs-220-astra-db-metadata.mintlify.app/ingestion/destination-connectors/astradb
=> Ingest v2: Astra DB connectors - add missing parameters/options

examplecode/tools/vectorshift.mdx
This link was to a third-party video that appears to no longer exist.
=> Remove broken video link in vectorshift.mdx

api-reference/workflow/destinations/overview.mdx, api-reference/workflow/overview.mdx, api-reference/workflow/sources/overview.mdx, snippets/general-shared-text/first-time-api-destination-connector.mdx, snippets/general-shared-text/first-time-api-source-connector.mdx, snippets/general-shared-text/first-time-ui-destination-connector.mdx, snippets/general-shared-text/first-time-ui-source-connector.mdx, ui/destinations/overview.mdx, ui/sources/overview.mdx
Stef asked for a few updates:
- Add a link from UI how-to pages to their API how-to counterparts, and vice versa.
- Add a blurb at the bottom of the blue boxes to keep reading to learn how. 😉 
Plus a few minor editorial updates for consistency and a bit more extensibility. 😉
=> UI/API: Further updates to getting-started notes at the beginning of connector how-to pages

api-reference/partition/examples.mdx, api-reference/partition/get-elements.mdx, api-reference/partition/sdk-jsts.mdx, snippets/examples/huggingchat.ts.mdx
- `res.elements` -> `res`.
- `res.elements?.[0]` stays unchanged though.
=> JavaScript/TypeScript SDK: res.elements -> res

examplecode/notebooks.mdx
See https://unstructured-53-notebook-mcp-python-2025-03-17.mintlify.app/examplecode/notebooks
=> Add link to notebook for the Unstructured Workflow Endpoint quickstart

examplecode/tools/langflow.mdx, examplecode/tools/vectorshift.mdx
Aligned Unstructured account and API setup steps with recent related how-to simplifications.
=> Langflow and VectorShift tutorials: simplify prerequisites

snippets/how-to-api/extract_image_block_types.py.mdx
See the updated code example in https://unstructured-53-extract-images-and-tables-no-vlm-2025-03-18.mintlify.app/api-reference/partition/extract-image-block-types
=> Partition Endpoint: extracting images and block types requires hi-res

api-reference/troubleshooting/api-key-url.mdx
See https://unstructured-53-docs-230-troubleshoot-keys-urls.mintlify.app/api-reference/troubleshooting/api-key-url
=> Troubleshooting API keys/URLs: simplify solutions, clean up UI steps

examplecode/tools/mcp.mdx, mint.json, snippets/general-shared-text/enterprise-self-hosted-differences.mdx, ui/account/api-key-url.mdx, ui/account/billing.mdx, ui/account/overview.mdx, ui/account/usage.mdx
See internal staged versions of these doc drafts: 
- Accounts overview: https://unstructured-53-account-overview-2025-03-18.mintlify.app/ui/account/overview
- Account billing: https://unstructured-53-account-overview-2025-03-18.mintlify.app/ui/account/billing
- Account usage: https://unstructured-53-account-overview-2025-03-18.mintlify.app/ui/account/usage
- Account API keys/URLs: https://unstructured-53-account-overview-2025-03-18.mintlify.app/ui/account/api-key-url
=> Account management: refactor and expand TOC to account for upcoming new account management pages

snippets/general-shared-text/confluence-cli-api.mdx, snippets/source_connectors/confluence.sh.mdx, snippets/source_connectors/confluence.v2.py.mdx
=> Ingest: Confluence source connector - separate auth parameters for API token and personal access token

ui/partitioning.mdx
See https://unstructured-53-docs-126-partition-languages.mintlify.app/ui/partitioning#supported-languages
=> Supported languages for Fast, High-Res, and VLM partitioning

examplecode/tools/mcp.mdx
See especially item number ... in
=> MCP server for the Workflow Endpoint: .env file how-to

mint.json
Point to product home page. Until now, this was pointing to the "For Enterprise" home page.
=> Fix link to Unstructured Product website in mint.json

snippets/general-shared-text/databricks-delta-table.mdx
Missing the `image_mime_type` and `image_base64` columns.
=> Delta Tables in Databricks destination connector: add missing columns to create table statement

snippets/general-shared-text/databricks-delta-table.mdx
Change `category_depth` from `INT` to `DOUBLE` in canonical `CREATE TABLE` statement.
=> Change field data type in databricks-delta-table.mdx

snippets/general-shared-text/pinecone-api-placeholders.mdx, snippets/general-shared-text/pinecone-cli-api.mdx, snippets/general-shared-text/pinecone-platform.mdx, snippets/general-shared-text/pinecone.mdx, snippets/general-shared-text/weaviate.mdx
This is now available to all users. 
See for example https://unstructured-53-docs-192-pinecone.mintlify.app/platform/destinations/pinecone
=> Platform: Pinecone index automatic management behavior

ui/workflows.mdx
After approving, please merge.
See https://unstructured-53-duplicate-workflow-2025-04-04.mintlify.app/ui/workflows#duplicate-a-workflow
=> UI: Duplicate a workflow

examplecode/notebooks.mdx
see PR title. 
Also adds a fix to a link for another notebook
=> Getting started with Unstructured and Databricks notebook

api-reference/troubleshooting/api-key-url.mdx, snippets/general-shared-text/enterprise-self-hosted-differences.mdx, snippets/general-shared-text/get-started-simple-api-only.mdx, snippets/general-shared-text/get-started-simple-ui-only.mdx, ui/account/organizations.mdx, ui/account/workspaces.mdx
Also, providing more links to self-hosted guidance where it seems to be useful.
=> Sign in URLs, API keys, and API URLs: Enterprise and self-hosted guidance differs from SaaS

snippets/general-shared-text/google-drive-api-placeholders.mdx, snippets/general-shared-text/google-drive-cli-api.mdx, snippets/general-shared-text/google-drive-platform.mdx, snippets/general-shared-text/google-drive.mdx
Very minor updates to indicate that shared drives are now also supported in addition to shared folders that were already supported.
=> Google Drive source connector: shared drives are now also supported

snippets/general-shared-text/enterprise-self-hosted-differences.mdx, ui/account/organizations.mdx, ui/account/overview.mdx, ui/account/roles.mdx, ui/account/workspaces.mdx
See top/beginning of:
- https://unstructured-53-account-update-2025-04-16.mintlify.app/ui/account/organizations
- https://unstructured-53-account-update-2025-04-16.mintlify.app/ui/account/workspaces
- https://unstructured-53-account-update-2025-04-16.mintlify.app/ui/account/roles
=> Some account docs apply only to organizational accounts

api-reference/workflow/overview.mdx
See:
- https://unstructured-53-check-connection-api-2025-04-17.mintlify.app/api-reference/workflow/overview#test-a-source-connector
- https://unstructured-53-check-connection-api-2025-04-17.mintlify.app/api-reference/workflow/overview#test-a-destination-connector
=> Workflow Endpoint: how to test connectors

snippets/general-shared-text/jira.mdx
Minor fix: Do not include the `/jira` part of the URL.
=> Fix incorrect guidance about Jira URLs

snippets/destination_connectors/s3.sh.mdx, snippets/destination_connectors/s3.v2.py.mdx, snippets/destination_connectors/s3_rest_create.mdx, snippets/destination_connectors/s3_sdk.mdx, snippets/general-shared-text/s3-api-placeholders.mdx, snippets/general-shared-text/s3-cli-api.mdx, snippets/general-shared-text/s3-platform.mdx, snippets/source_connectors/s3.sh.mdx, snippets/source_connectors/s3.v2.py.mdx, snippets/source_connectors/s3_rest_create.mdx, snippets/source_connectors/s3_sdk.mdx
See for example **AWS Key**, **AWS Secret Key**, and **STS Token**, in about the middle of https://unstructured-53-s3-sts-2025-04-17.mintlify.app/ui/sources/s3
=> S3 connectors: if using AWS STS, must specify access key, secret access key, and STS token (not just STS token)

snippets/destination_connectors/redis.sh.mdx, snippets/destination_connectors/redis.v2.py.mdx, snippets/destination_connectors/redis_rest_create.mdx, snippets/destination_connectors/redis_sdk.mdx, snippets/general-shared-text/redis-api-placeholders.mdx, snippets/general-shared-text/redis-cli-api.mdx, snippets/general-shared-text/redis-platform.mdx
This optional setting prepends a custom string to each element's `element_id`. This is useful for distinguishing between different data sets in the same Redis instance. If not specified, nothing is prepended to each element's `element_id`.
=> Redis destination connector: add support for custom element_id prefixes

snippets/general-shared-text/s3.mdx
For example in context, see the sidebar that begins with "AWS STS credentials can be valid for as little as..." in https://unstructured-53-s3-sts-2025-04-24.mintlify.app/ui/sources/s3
=> S3 connectors: how to refresh expired AWS STS session tokens

api-reference/workflow/overview.mdx, api-reference/workflow/workflows.mdx, ui/workflows.mdx
You can now use the Python SDK to create local-to-local and local-to-remote workflows programmatically. 
You can also now use REST to create local-to-remote workflows. This is an addition to the already-existing ability to create local-to-local workflows. 
The following limitations of workflows with local connectors (regardless of whether the destination is local or remote) are noted throughout, specifically:
- You can't set these workflows to run on a repeating schedule.
- You can run these workflows only with REST clients such as `curl` or Postman. You can't run them with the Unstructured Python SDK or the Unstructured UI (even though they are visible in the UI).
Also noted, for completeness:
- If you create a workflow in the UI with a local connector, you can't save it from there. 
- …
=> API: Local-to-local workflows for Python, local-to-remote workflows for REST and Python

snippets/general-shared-text/ibm-watsonxdata-api-placeholders.mdx, snippets/general-shared-text/ibm-watsonxdata-cli-api.mdx, snippets/general-shared-text/ibm-watsonxdata-platform.mdx, snippets/general-shared-text/ibm-watsonxdata.mdx
See the updated `CREATE TABLE` statement, the new Python script, and additions to **Max Connection Retries** and **Max Retries**, in https://unstructured-53-ibm-watsonxdata-2025-04-22.mintlify.app/ui/destinations/ibm-watsonxdata
=> IBM watsonx.data destination connector: improve performance with partitioning, metadata cleanup, and increased retries

snippets/general-shared-text/jira-api-placeholders.mdx, snippets/general-shared-text/jira-cli-api.mdx, snippets/general-shared-text/jira-platform.mdx, snippets/source_connectors/jira.sh.mdx, snippets/source_connectors/jira.v2.py.mdx, snippets/source_connectors/jira_rest_create.mdx, snippets/source_connectors/jira_sdk.mdx
See for example the **Cloud** setting at the very end/bottom of https://unstructured-53-docs-260-jira.mintlify.app/ui/sources/jira
=> Jira source connector: restore 'is cloud' setting

snippets/general-shared-text/sharepoint-api-placeholders.mdx, snippets/general-shared-text/sharepoint-cli-api.mdx, snippets/general-shared-text/sharepoint-platform.mdx, snippets/general-shared-text/sharepoint.mdx, snippets/source_connectors/sharepoint.sh.mdx, snippets/source_connectors/sharepoint.v2.py.mdx, snippets/source_connectors/sharepoint_rest_create.mdx, snippets/source_connectors/sharepoint_sdk.mdx
- Username/password authentication is now also supported. 
- Rearranged requirements and parameter listings to better match the UI and the (now) two supported authentication flows.
- Clarified the format for specifying a non-default site path to begin ingesting files from.
See:
- UI: https://unstructured-53-docs-268-sharepoint.mintlify.app/ui/sources/sharepoint
- API: https://unstructured-53-docs-268-sharepoint.mintlify.app/api-reference/workflow/sources/sharepoint
- Ingest: https://unstructured-53-docs-268-sharepoint.mintlify.app/ingestion/source-connectors/sharepoint
=> SharePoint source connector: add username/password auth, clarify ingest path format

api-reference/supported-file-types.mdx, snippets/general-shared-text/supported-file-types-platform.mdx
See (same list for both):
- UI: https://unstructured-53-supported-file-types-2025-05-15.mintlify.app/ui/supported-file-types
- API: https://unstructured-53-supported-file-types-2025-05-15.mintlify.app/api-reference/supported-file-types
=> Updating supported file types for the Unstructured UI/API

snippets/quickstarts/single-file-ui.mdx
To view, scroll down to the first embedded video in https://unstructured-53-playground-video-2025-05-20.mintlify.app/welcome#unstructured-ui-quickstart
=> Quickstarts: add link from single-file UI quickstart to new how-to video

snippets/general-shared-text/supported-file-types-platform.mdx, welcome.mdx
The Welcome page was incorrectly pointing to list of file types supported by open source and giving the impression this was the same list for the Platform UI/API. This PR now points to the correct list. 
(Also needed to remove a pesky "Notes" heading that was making for some awkward TOC presentations.)
See https://unstructured-53-file-types-2025-05-20.mintlify.app/welcome#supported-file-types
=> File type updates for UI/API on Welcome page

open-source/introduction/supported-file-types.mdx, snippets/general-shared-text/supported-file-types-open-source.mdx
Clarifying on the page listing the supported file types for open source that this list indeed applies only to open source. 
Also renaming the file containing the list that this page references, to clearly differentiate the open source list from the non-open source one. 😓 
See https://unstructured-53-open-source-file-types-2025-05-20.mintlify.app/open-source/introduction/supported-file-types
=> File type updates for open source

api-reference/workflow/workflows.mdx, snippets/general-shared-text/enrichment-image-summary-hi-res-only.mdx, snippets/general-shared-text/enrichment-images-tables-hi-res-only.mdx, snippets/general-shared-text/enrichment-table-summary-hi-res-only.mdx, snippets/general-shared-text/enrichment-table-to-html-hi-res-only.mdx, snippets/quickstarts/single-file-ui.mdx, ui/enriching/image-descriptions.mdx, ui/enriching/overview.mdx, ui/enriching/table-descriptions.mdx, ui/enriching/table-to-html.mdx, ui/summarizing.mdx, ui/workflows.mdx
More external customers (and now internal users) are encountering this, resulting in hung workflows and no-ops, so making this guidance clearer throughout the docs. 
See for example the yellow warning box in https://unstructured-53-hi-res-enrichments-2025-05-22.mintlify.app/ui/enriching/overview
=> Image/table enrichments work only with High Res partitioning

docs.json, examplecode/tools/jq.mdx
See https://unstructured-53-jq-2025-06-10.mintlify.app/examplecode/tools/jq
=> How to use jq

ui/chunking.mdx
After spending several hours testing the previously-published usage note's admonitions with a variety of different chunking settings and document types, there seemed to be no impact on the results. If this surfaces as a significant issue with customers, the removed content can of course be added back in later with additional explanation as necessary.
Also, added slightly more commentary to explain some of the remaining conceptual diagrams.
=> Chunking overview: remove usage note about not setting combine text >= new after n characters

snippets/concepts/document-elements.mdx, ui/document-elements.mdx
See https://unstructured-53-email-metadata-2025-06-17.mintlify.app/ui/document-elements#email
=> Document elements and metadata overview: add missing email metadata fields

api-reference/workflow/sources/overview.mdx, api-reference/workflow/sources/slack.mdx, docs.json, snippets/general-shared-text/slack-api-placeholders.mdx, snippets/general-shared-text/slack.mdx, snippets/source_connectors/slack_rest_create.mdx, snippets/source_connectors/slack_sdk.mdx
See https://unstructured-53-doc-16-slack-api.mintlify.app/api-reference/workflow/sources/slack
=> API: Slack source connector

snippets/general-shared-text/mongodb.mdx
See especially the yellow warning box about a third of way down the page in https://unstructured-53-doc-22-mongodb-atlas.mintlify.app/ui/sources/mongodb
Also, removed the embedded how-to video showing creation of a Free/M0 cluster for now, until I can reshoot a new one.
=> MongoDB connectors: clusters with only SCRAM-SHA-1 are not supported

open-source/introduction/overview.mdx
Per discussion with Stef and Sudarshan. See https://unstructured-53-open-source-2025-06-23.mintlify.app/open-source/introduction/overview#limits
=> Open source: additional limits

snippets/general-shared-text/mongodb.mdx
Re-shot the how-to video to show creating an `M10` cluster that included SCRAM-SHA-256 for authentication. (The previous version showed creating an `M0` (`Free`) cluster that only includes SCRAM-SHA-1 for authentication, which we no longer support.)
See for example the embedded video in https://unstructured-53-doc-23-mongodb-atlas.mintlify.app/ui/sources/mongodb
=> MongoDB connectors: update embedded how-to video

docs.json, examplecode/tools/google-drive-events.mdx
See https://unstructured-53-google-drive-events-2025-07-03.mintlify.app/examplecode/tools/google-drive-events
=> Google Drive source connector: workflow run trigger

examplecode/tools/sharepoint-events.mdx
See https://unstructured-53-sharepoint-events-2025-07-11.mintlify.app/examplecode/tools/sharepoint-events#step-3%3A-create-a-power-automate-flow > item 15, `unstructured-api-key` setting
=> SharePoint source connector: Power Automate flow example - use key vault value instead of hard-coded API key

api-reference/partition/chunking.mdx, api-reference/workflow/overview.mdx, open-source/core-functionality/chunking.mdx, open-source/core-functionality/overview.mdx, open-source/how-to/embedding.mdx, open-source/introduction/overview.mdx, snippets/concepts/glossary.mdx, snippets/quickstarts/single-file-ui.mdx, ui/embedding.mdx, ui/overview.mdx, welcome.mdx
Add "agentic AI" to the list of uses.
Consistent phrasing of "retrieval-augmented generation (RAG)."
=> RAG and agentic AI

api-reference/workflow/workflows.mdx
See https://unstructured-53-ner-prompt-2025-07-17.mintlify.app/api-reference/workflow/workflows#named-entity-recognition-ner-task
=> Workflow Endpoint: NER workflow node - guidance for providing an alternative prompt

examplecode/tools/s3-vectors.mdx
Forgot an important index setup item the first time around. 
Now see items 6-8 in "Step 2: Add the vector index to the bucket:" https://unstructured-53-s3-vectors-2025-07-18.mintlify.app/examplecode/tools/s3-vectors#step-2%3A-add-the-vector-index-to-the-bucket
=> Amazon S3 Vectors and Unstructured: added missing step for non-filterable metadata

api-reference/workflow/errors.mdx, docs.json
See https://unstructured-53-python-sdk-2025-07-30.mintlify.app/api-reference/workflow/errors
=> Python SDK: new classes for more robust error handling for the Workflow Endpoint

api-reference/workflow/migration.mdx, docs.json
See https://unstructured-53-workflow-migration-2025-08-06.mintlify.app/api-reference/workflow/migration
=> Workflow Endpoint: migration guidance for deprecated ConnectorConfigInput and ConnectorType classes

snippets/general-shared-text/onedrive.mdx
=> OneDrive connectors: supported authentication types

snippets/general-shared-text/chroma-cli-api.mdx, snippets/general-shared-text/chroma.mdx
Hey!
I added instructions on how to configure unstructured so it can connect to Chroma Cloud
=> Update docs for Chroma Cloud

snippets/general-shared-text/confluence-api-placeholders.mdx, snippets/general-shared-text/confluence-cli-api.mdx, snippets/general-shared-text/confluence-platform.mdx, snippets/general-shared-text/confluence.mdx, snippets/source_connectors/confluence.sh.mdx, snippets/source_connectors/confluence.v2.py.mdx, snippets/source_connectors/confluence_rest_create.mdx, snippets/source_connectors/confluence_sdk.mdx
The connector uses space keys, not space names. Space keys must be unique across a Confluence instance. Space names should also be unique--but this is not strictly required. 
See coverage of space keys in:
- https://unstructured-53-confluence-2025-08-21.mintlify.app/ui/sources/confluence
- https://unstructured-53-confluence-2025-08-21.mintlify.app/ui/sources/confluence
- https://unstructured-53-confluence-2025-08-21.mintlify.app/open-source/ingestion/source-connectors/confluence
=> Confluence source connector: specify space keys, not space names

ui/account/organizations.mdx, ui/account/roles.mdx, ui/account/workspaces.mdx
- For the **Operator** role, changed **No** to **Yes** for Worfkows -> Create, Edit, and Delete.
- Added a new permission set Workflow -> Save; setting to **Viewer** = **No** , **Operator** = **Yes**, **Developer** = **Yes**, and **Workspace Administrator** =  **Yes**
- Added a new permission set Workflow -> Duplicate; setting to **Viewer** = **No** , **Operator** = **Yes**, **Developer** = **Yes**, and **Workspace Administrator** =  **Yes**
- Added a new permission set Workflow -> Activate and deactivate; setting to **Viewer** = **No** , **Operator** = **Yes**, **Developer** = **Yes**, and **Workspace Administrator** =  **Yes**
Also:
- Copied the role descriptions out of the UI into the docs where those roles and listed.
- Updated **Super Admin** to **Super Administrator** throughout as …
=> RBAC: Expand Operator role permissions

README.md
Make it easy for developers to find the docs site in production.
=> Add a link to the live documentation website

api-reference/overview.mdx, api-reference/partition/overview.mdx, api-reference/partition/quickstart.mdx, api-reference/workflow/overview.mdx, docs.json, snippets/quickstarts/platform.mdx, ui/destinations/overview.mdx, ui/destinations/pinecone-destination-quickstart.mdx, ui/quickstart.mdx, ui/sources/dropbox-source-quickstart.mdx, ui/sources/overview.mdx
This PR makes it easier and quicker for customers to find and jump into the various quickstarts without needing to read a bunch of documentation first.
=> Tie all of the quickstarts together

snippets/general-shared-text/snowflake.mdx
See for example https://unstructured-53-snowflake-2025-09-03.mintlify.app/ui/sources/snowflake
=> Snowflake connectors: add more how-to videos - create human users, create service users, create PATs

snippets/general-shared-text/ibm-watsonxdata.mdx, snippets/general-shared-text/milvus.mdx
- Fix lead-in lettering for sublists. 
- Change default embedding dimensions to match those offered by IBM, and add a note that dimensions need to match with your chosen model.
- Update the default schema to include the missing `text` field. 
- Update the collection creation code snippet to use `client` methods as recommended instead of `connection` methods, as well as the recommended approach to build the index separately.
=> Updates to Milvus and IBM watsonx.data connectors
